name: tiddit_sv
description: Identify chromosomal rearrangements.
keywords:
  - structural
  - variants
  - vcf
tools:
  - sv:
      description: Search for structural variants.
      homepage: https://github.com/SciLifeLab/TIDDIT
      documentation: https://github.com/SciLifeLab/TIDDIT/blob/master/README.md
      doi: 10.12688/f1000research.11168.1
      licence: ["GPL-3.0-or-later"]
      identifier: biotools:tiddit
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM file
        pattern: "*.{bam,cram}"
    - input_index:
        type: file
        description: BAM/CRAM index file
        pattern: "*.{bai,crai}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test_fasta']`
    - fasta:
        type: file
        description: Input FASTA file
        pattern: "*.{fasta,fa}"
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information from bwa index
          e.g. `[ id:'test_bwa-index' ]`
    - bwa_index:
        type: file
        description: BWA genome index files
        pattern: "Directory containing BWA index *.{amb,ann,bwt,pac,sa}"
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf":
          type: file
          description: vcf
          pattern: "*.{vcf}"
  - ploidy:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.ploidies.tab":
          type: file
          description: tab
          pattern: "*.{ploidies.tab}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@maxulysse"
maintainers:
  - "@maxulysse"
