//
// Validation against truth.
//

include { RTGTOOLS_VCFEVAL                 } from '../../modules/nf-core/rtgtools/vcfeval/main'
// or do it with hap.py???

workflow VCF_VALIDATE_SMALL_VARIANTS {

    take:

    main:
    versions = Channel.empty()
        // input: of rtgtools/vcfeval
        // tuple val(meta), path(query_vcf), path(query_vcf_tbi), path(truth_vcf), path(truth_vcf_tbi), path(truth_bed), path(evaluation_bed)
        // query_vcf = generated by sarek run
        // truth_vcf = denoted in test_data or somewhere
        // tuple val(meta2), path(sdf)

        // if benchmark = true then do "normal" sarek run and compare to truth sample here
        // needs param which truth sample was used maybe?
        // get truth, normalize truth

        RTGTOOLS_VCFEVAL ( ch_vcfeval_in, ch_sdf )

    emit:
        versions        = ch_versions // channel: [ path(versions.yml) ]
}
