name: gatk4_mergemutectstats
description: Merges mutect2 stats generated on different intervals/regions
keywords:
  - mutectstats
  - merge
tools:
  - gatk4:
      description: Genome Analysis Toolkit (GATK4)
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      tool_dev_url: https://github.com/broadinstitute/gatk
      doi: "10.1158/1538-7445.AM2017-3590"
      licence: ["BSD-3-clause"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - stats:
      type: (list of) file(s)
      description: Stats file
      pattern: "*.{stats}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - stats:
      type: file
      description: Stats file
      pattern: "*.vcf.gz.stats"

authors:
  - "@FriederikeHanssen"
