name: gatk4_markduplicates
description: This tool locates and tags duplicate reads in a BAM or SAM file, where
  duplicate reads are defined as originating from a single fragment of DNA.
keywords:
  - bam
  - gatk4
  - markduplicates
  - sort
tools:
  - gatk4:
      description: Developed in the Data Sciences Platform at the Broad Institute, the
        toolkit offers a wide variety of tools with a primary focus on variant discovery
        and genotyping. Its powerful processing engine and high-performance computing
        features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard-
      tool_dev_url: https://github.com/broadinstitute/gatk
      doi: 10.1158/1538-7445.AM2017-3590
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Sorted BAM file
        pattern: "*.{bam}"
        ontologies: []
  - fasta:
      type: file
      description: Fasta file
      pattern: "*.{fasta}"
      ontologies: []
  - fasta_fai:
      type: file
      description: Fasta index file
      pattern: "*.{fai}"
      ontologies: []
output:
  cram:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*cram":
          type: file
          description: Marked duplicates CRAM file
          pattern: "*.{cram}"
          ontologies: []
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*bam":
          type: file
          description: Marked duplicates BAM file
          pattern: "*.{bam}"
          ontologies: []
  crai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.crai":
          type: file
          description: CRAM index file
          pattern: "*.{cram.crai}"
          ontologies: []
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bai":
          type: file
          description: BAM index file
          pattern: "*.{bam.bai}"
          ontologies: []
  metrics:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.metrics":
          type: file
          description: Duplicate metrics file generated by GATK
          pattern: "*.{metrics.txt}"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@ajodeh-juma"
  - "@FriederikeHanssen"
  - "@maxulysse"
maintainers:
  - "@ajodeh-juma"
  - "@FriederikeHanssen"
  - "@maxulysse"
