name: bedtools_merge
description: combines overlapping or “book-ended” features in an interval file into a single feature which spans all of the combined features.
keywords:
  - bed
  - merge
  - bedtools
  - overlapped bed
tools:
  - bedtools:
      description: |
        A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
      documentation: https://bedtools.readthedocs.io/en/latest/content/tools/merge.html
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: Input BED file
      pattern: "*.{bed}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: Overlapped bed file with combined features
      pattern: "*.{bed}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@edmundmiller"
  - "@sruthipsuresh"
  - "@drpatelh"
maintainers:
  - "@edmundmiller"
  - "@sruthipsuresh"
  - "@drpatelh"
