name: deepvariant_callvariants
description: Call variants from the examples produced by make_examples
keywords:
  - variant calling
  - machine learning
  - neural network
tools:
  - deepvariant:
      description: DeepVariant is an analysis pipeline that uses a deep neural network
        to call genetic variants from next-generation DNA sequencing data
      homepage: https://github.com/google/deepvariant
      documentation: https://github.com/google/deepvariant
      tool_dev_url: https://github.com/google/deepvariant
      doi: "10.1038/nbt.4235"
      licence: ["BSD-3-clause"]
      identifier: biotools:deepvariant
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - make_examples_tfrecords:
        type: file
        description: The actual sharded input files, from DEEPVARIANT_MAKEEXAMPLES process
        pattern: "*.gz"
output:
  - call_variants_tfrecords:
      - meta:
          type: list
          description: |
            Each output contains: unique ID string from input channel, meta, tfrecord file with variant calls.
      - ${prefix}.call-*-of-*.tfrecord.gz:
          type: list
          description: |
            Each output contains: unique ID string from input channel, meta, tfrecord file with variant calls.
  - versions:
      - versions.yml:
          type: file
          description: File containing software version
          pattern: "versions.yml"
authors:
  - "@abhi18av"
  - "@ramprasadn"
  - "@fa2k"
maintainers:
  - "@abhi18av"
  - "@ramprasadn"
