channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::bioconductor-org.hs.eg.db=3.18.0
  - bioconda::bioconductor-purecn=2.8.1
  - bioconda::bioconductor-txdb.hsapiens.ucsc.hg19.knowngene=3.2.2
  - bioconda::bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.18.0
  - conda-forge::r-optparse=1.7.5
  - conda-forge::r-r.utils=2.12.3
