name: freebayes
description: A haplotype-based variant detector
keywords:
  - variant caller
  - SNP
  - genotyping
  - somatic variant calling
  - germline variant calling
  - bacterial variant calling
  - bayesian
tools:
  - freebayes:
      description: Bayesian haplotype-based polymorphism discovery and genotyping
      homepage: https://github.com/freebayes/freebayes
      documentation: https://github.com/freebayes/freebayes
      tool_dev_url: https://github.com/freebayes/freebayes
      doi: "10.48550/arXiv.1207.3907"
      licence: ["MIT"]
      identifier: biotools:freebayes
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input_1:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
    - input_1_index:
        type: file
        description: BAM/CRAM/SAM index file
        pattern: "*.{bai,crai}"
    - input_2:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
    - input_2_index:
        type: file
        description: BAM/CRAM/SAM index file
        pattern: "*.{bai,crai}"
    - target_bed:
        type: file
        description: Optional - Limit analysis to targets listed in this BED-format
          FILE.
        pattern: "*.bed"
  - - ref_meta:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test_reference' ]
    - fasta:
        type: file
        description: reference fasta file
        pattern: ".{fa,fa.gz,fasta,fasta.gz}"
  - - ref_idx_meta:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test_reference' ]
    - fasta_fai:
        type: file
        description: reference fasta file index
        pattern: "*.{fa,fasta}.fai"
  - - samples_meta:
        type: map
        description: |
          Groovy Map containing meta information for the samples file.
          e.g. [ id:'test_samples' ]
    - samples:
        type: file
        description: Optional - Limit analysis to samples listed (one per line) in the
          FILE.
        pattern: "*.txt"
  - - populations_meta:
        type: map
        description: |
          Groovy Map containing meta information for the populations file.
          e.g. [ id:'test_populations' ]
    - populations:
        type: file
        description: Optional - Each line of FILE should list a sample and a population
          which it is part of.
        pattern: "*.txt"
  - - cnv_meta:
        type: map
        description: |
          Groovy Map containing meta information for the cnv file.
          e.g. [ id:'test_cnv' ]
    - cnv:
        type: file
        description: |
          A copy number map BED file, which has either a sample-level ploidy:
          sample_name copy_number
          or a region-specific format:
          seq_name start end sample_name copy_number
        pattern: "*.bed"
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: Compressed VCF file
          pattern: "*.vcf.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software version
          pattern: "versions.yml"
authors:
  - "@maxibor"
  - "@FriederikeHanssen"
  - "@maxulysse"
maintainers:
  - "@maxibor"
  - "@FriederikeHanssen"
  - "@maxulysse"
