name: fgbio_callmolecularconsensusreads
description: Calls consensus sequences from reads with the same unique molecular tag.

keywords:
  - UMIs
  - consensus sequence
  - bam
  - sam
tools:
  - fgbio:
      description: Tools for working with genomic and high throughput sequencing data.
      homepage: https://github.com/fulcrumgenomics/fgbio
      documentation: http://fulcrumgenomics.github.io/fgbio/
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false, collapse:false ]
  - bam:
      type: file
      description: |
        The input SAM or BAM file.
      pattern: "*.{bam,sam}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: |
        Output SAM or BAM file to write consensus reads.
      pattern: "*.{bam,sam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@sruthipsuresh"
