# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "deepsomatic"
description: DeepSomatic is an extension of deep learning-based variant caller DeepVariant
  that takes aligned reads (in BAM or CRAM format) from tumor and normal data, produces pileup
  image tensors from them, classifies each tensor using a convolutional neural network, and
  finally reports somatic variants in a standard VCF or gVCF file.
keywords:
  - variant calling
  - machine learning
  - neural network
tools:
  - "deepsomatic":
      description: ""
      homepage: "https://github.com/google/deepsomatic"
      documentation: "https://github.com/google/deepsomatic"
      tool_dev_url: "https://github.com/google/deepsomatic"
      doi: "10.1101/2024.08.16.608331"
      licence: ["BSD-3-clause"]
      identifier: "biotools:deepsomatic"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input_normal:
        type: file
        description: BAM/CRAM file
        pattern: "*.bam/cram"
    - index_normal:
        type: file
        description: Index of BAM/CRAM file
        pattern: "*.bai/crai"
    - input_tumor:
        type: file
        description: BAM/CRAM file
        pattern: "*.bam/cram"
    - index_tumor:
        type: file
        description: Index of BAM/CRAM file
        pattern: "*.bai/crai"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - intervals:
        type: file
        description: file containing intervals
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.fasta"
  - - meta4:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: Index of reference fasta file
        pattern: "*.fai"
  - - meta5:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - gzi:
        type: file
        description: GZI index of reference fasta file
        pattern: "*.gzi"

output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.vcf.gz":
          type: file
          description: Compressed VCF file
          pattern: "*.vcf.gz"
  - vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.vcf.gz.tbi":
          type: file
          description: Index of compressed VCF file
          pattern: "*.vcf.gz.tbi"
  - gvcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.g.vcf.gz":
          type: file
          description: Compressed GVCF file
          pattern: "*.g.vcf.gz"
  - gvcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "${prefix}.g.vcf.gz.tbi":
          type: file
          description: Index of compressed Genotyped VCF file
          pattern: "*.g.vcf.gz.tbi"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@vaxyzek"
maintainers:
  - "@vaxyzek"
