name: multiqc
description: Aggregate results from bioinformatics analyses across many samples
  into a single report
keywords:
  - QC
  - bioinformatics tools
  - Beautiful stand-alone HTML report
tools:
  - multiqc:
      description: |
        MultiQC searches a given directory for analysis logs and compiles a HTML report.
        It's a general use tool, perfect for summarising the output from numerous bioinformatics tools.
      homepage: https://multiqc.info/
      documentation: https://multiqc.info/docs/
      licence:
        - "GPL-3.0-or-later"
      identifier: biotools:multiqc
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'sample1', single_end:false ]
    - multiqc_files:
        type: file
        description: |
          List of reports / files recognised by MultiQC, for example the html and zip output of FastQC
        ontologies: []
    - multiqc_config:
        type: file
        description: Optional config yml for MultiQC
        pattern: "*.{yml,yaml}"
        ontologies:
          - edam: http://edamontology.org/format_3750
    - multiqc_logo:
        type: file
        description: Optional logo file for MultiQC
        pattern: "*.{png}"
        ontologies: []
    - replace_names:
        type: file
        description: |
          Optional two-column sample renaming file. First column a set of
          patterns, second column a set of corresponding replacements. Passed via
          MultiQC's `--replace-names` option.
        pattern: "*.{tsv}"
        ontologies:
          - edam: http://edamontology.org/format_3475
    - sample_names:
        type: file
        description: |
          Optional TSV file with headers, passed to the MultiQC --sample_names
          argument.
        pattern: "*.{tsv}"
        ontologies:
          - edam: http://edamontology.org/format_3475
output:
  report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*.html":
          type: file
          description: MultiQC report file
          pattern: ".html"
          ontologies: []
  data:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*_data":
          type: directory
          description: MultiQC data dir
          pattern: "multiqc_data"
  plots:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'sample1', single_end:false ]
      - "*_plots":
          type: file
          description: Plots created by MultiQC
          pattern: "*_plots"
          ontologies: []
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - multiqc:
          type: string
          description: The tool name
      - multiqc --version | sed "s/.* //g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
maintainers:
  - "@abhi18av"
  - "@bunop"
  - "@drpatelh"
  - "@jfy133"
containers:
  conda:
    linux/amd64:
      lock_file: modules/nf-core/multiqc/.conda-lock/linux_amd64-bd-839587b417d23042_1.txt
    linux/arm64:
      lock_file: modules/nf-core/multiqc/.conda-lock/linux_arm64-bd-3e45d17b40a576b4_1.txt
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/multiqc:1.35--839587b417d23042
      build_id: bd-839587b417d23042_1
      scan_id: sc-f87d7a31551c029f_1
    linux/arm64:
      name: community.wave.seqera.io/library/multiqc:1.35--3e45d17b40a576b4
      build_id: bd-3e45d17b40a576b4_1
      scan_id: sc-1d0cf4ed1a4b61e0_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/multiqc:1.35--cb7458fda84d6393
      build_id: bd-cb7458fda84d6393_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/12/1297c0f5075c19486da167ebf1b6136907d6b5339697b87b29fda335221785b3/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/multiqc:1.35--f79e87603d312ac0
      build_id: bd-f79e87603d312ac0_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/c0/c007304153702edc622f1a76b41505e7fca65c7145e5b8b2ddce62a5c59af207/data
