name: unzip
description: Unzip ZIP archive files
keywords:
  - unzip
  - decompression
  - zip
  - archiving
tools:
  - unzip:
      description: p7zip is a quick port of 7z.exe and 7za.exe (command line version
        of 7zip, see www.7-zip.org) for Unix.
      homepage: https://sourceforge.net/projects/p7zip/
      documentation: https://sourceforge.net/projects/p7zip/
      tool_dev_url: https://sourceforge.net/projects/p7zip"
      licence: ["LGPL-2.1-or-later"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - archive:
        type: file
        description: ZIP file
        pattern: "*.zip"
output:
  - unzipped_archive:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/:
          type: directory
          description: Directory contents of the unzipped archive
          pattern: "${archive.baseName}/"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@jfy133"
maintainers:
  - "@jfy133"
