name: unzip
description: Unzip ZIP archive files
keywords:
  - unzip
  - decompression
  - zip
  - archiving
tools:
  - unzip:
      description: p7zip is a quick port of 7z.exe and 7za.exe (command line
        version of 7zip, see www.7-zip.org) for Unix.
      homepage: https://sourceforge.net/projects/p7zip/
      documentation: https://sourceforge.net/projects/p7zip/
      tool_dev_url: https://sourceforge.net/projects/p7zip"
      licence:
        - "LGPL-2.1-or-later"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - archive:
        type: file
        description: ZIP file
        pattern: "*.zip"
        ontologies:
          - edam: http://edamontology.org/format_3987
output:
  unzipped_archive:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/:
          type: directory
          description: Directory contents of the unzipped archive
          pattern: "${archive.baseName}/"
  versions_7za:
    - - ${task.process}:
          type: string
          description: The name of the process
      - 7za:
          type: string
          description: The name of the tool
      - 7za 2>&1 | sed -n '2s/^.* \([0-9.]*\) .*/\1/p':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - 7za:
          type: string
          description: The name of the tool
      - 7za 2>&1 | sed -n '2s/^.* \([0-9.]*\) .*/\1/p':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@jfy133"
maintainers:
  - "@jfy133"
