name: msisensorpro_msi

description: evaluate MSI using paired tumor-normal sequencing data
keywords:
  - microsatellite
tools:
  - msisensor:
      description: MSIsensor-pro is an updated version of msisensor
      homepage: https://github.com/xjtu-omics/msisensor-pro
      documentation: None
      tool_dev_url: None
      doi: "doi.org/10.1016/j.gpb.2020.02.001"
      licence: ['free for non-commercial use by academic, government, and non-profit/not-for-profit institutions']

input:
  - meta:
      type: map
      description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - bam_normal:
      type: file
      description: |
        BAM file from normal tissue
  - bai_normal:
      type: file
      description: |
          Index for the BAM file from normal tissue
  - bam_tumor:
      type: file
      description: |
          BAM file from tumor tissue
  - bai_tumor:
      type: file
      description: |
          Index for the BAM file from tumor tissue
  - msisensor_scan:
      type: file
      description: |
          Output file from msisensor-pro scan module

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - list:
      type: file
      description: |
        msisensor-pro final report and associated files (dis, germline, somatic)
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@maxulysse"
