exclude:
  - tags: "bcftools/annotate"
  - tags: "bcftools/concat"
  - tags: "bcftools/mpileup"
  - tags: "bcftools/sort"
  - tags: "bwa/index"
  - tags: "bwa/mem"
  - tags: "bwamem2/index"
  - tags: "bwamem2/mem"
  - tags: "cat/cat"
  - tags: "cat/fastq"
  - tags: "cnvkit/antitarget"
  - tags: "cnvkit/batch"
  - tags: "cnvkit/reference"
  - tags: "deepvariant"
  - tags: "dragmap/align"
  - tags: "dragmap/hashtable"
  - tags: "ensemblvep/download"
  - tags: "ensemblvep/vep"
  - tags: "fastp"
  - tags: "fastqc"
  - tags: "fgbio/fastqtobam"
  - tags: "freebayes"
  - tags: "gatk4/applybqsr"
  - tags: "gatk4/baserecalibrator"
  - tags: "gatk4/estimatelibrarycomplexity"
  - tags: "gatk4/genomicsdbimport"
  - tags: "gatk4/haplotypecaller"
  - tags: "gatk4/markduplicates"
  - tags: "gatk4/mergevcfs"
  - tags: "gatk4/mutect2"
  - tags: "gatk4spark/applybqsr"
  - tags: "gatk4spark/markduplicates"
  - tags: "gawk"
  - tags: "lofreq/callparallel"
  - tags: "mosdepth"
  - tags: "multiqc"
  - tags: "ngscheckmate/ncm"
  - tags: "samblaster"
  - tags: "samtools/convert"
  - tags: "samtools/mpileup"
  - tags: "samtools/stats"
  - tags: "snpeff/snpeff"
  - tags: "strelka/germline"
  - tags: "strelka/somatic"
  - tags: "subworkflows/utils_nfvalidation_plugin"
  - tags: "tabix/bgziptabix"
  - tags: "tabix/tabix"
  - tags: "tiddit/sv"
  - tags: "untar"
