name: cnvkit_antitarget
description:
keywords:
  - cvnkit
  - antitarget
tools:
  - cnvkit:
      description: |
        CNVkit is a Python library and command-line software toolkit to infer and visualize copy number from high-throughput DNA sequencing data.
        It is designed for use with hybrid capture, including both whole-exome and custom target panels, and short-read sequencing platforms such as Illumina and Ion Torrent.
      homepage: https://cnvkit.readthedocs.io/en/stable/index.html
      documentation: https://cnvkit.readthedocs.io/en/stable/index.html
      tool_dev_url: "https://github.com/etal/cnvkit"
      doi: 10.1371/journal.pcbi.1004873
      licence: ["Apache-2.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - targets:
      type: file
      description: File containing genomic regions
      pattern: "*.{bed}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: File containing off-target regions
      pattern: "*.{bed}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@SusiJo"
