name: gatk4_intervallisttobed
description: Converts an Picard IntervalList file to a BED file.
keywords:
  - bed
  - conversion
  - gatk4
  - interval
tools:
  - gatk4:
      description: Genome Analysis Toolkit (GATK4)
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      tool_dev_url: https://github.com/broadinstitute/gatk
      doi: "10.1158/1538-7445.AM2017-3590"
      licence: ["BSD-3-clause"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - intervals:
        type: file
        description: IntervalList file
output:
  - bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bed":
          type: file
          description: BED file
          pattern: "*.bed"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@FriederikeHanssen"
maintainers:
  - "@FriederikeHanssen"
