repository_type: pipeline
lint:
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .github/workflows/ci.yml
    - assets/nf-core-sarek_logo_light.png
    - docs/images/nf-core-sarek_logo_dark.png
    - docs/images/nf-core-sarek_logo_light.png
    - lib/NfcoreTemplate.groovy
    - lib/NfcoreSchema.groovy
  schema_params: False
  template_strings: False
  multiqc_config: False
