repository_type: pipeline
lint:
  files_exist:
    - conf/modules.config
    - conf/test.config
    - conf/test_full.config
  files_unchanged:
    - assets/multiqc_config.yml
    - assets/nf-core-sarek_logo_light.png
    - docs/images/nf-core-sarek_logo_dark.png
    - docs/images/nf-core-sarek_logo_light.png
    - lib/NfcoreTemplate.groovy
    - lib/NfcoreSchema.groovy
  template_strings: False
  schema_params: False
