lint:
  files_unchanged:
    - .github/workflows/linting.yml
    - assets/multiqc_config.yaml
    - assets/nf-core-sarek_logo.png
    - docs/images/nf-core-sarek_logo.png
    - lib/NfcoreTemplate.groovy
