sudo: required
language: python
jdk: openjdk8
services: docker

addons:
  apt:
    update: true

python: '3.6'
cache: pip

matrix:
  fast_finish: true

env:
  global:
    - NXF_VER=19.04.0
  matrix:
    - TEST=SOMATIC
    - TEST=GERMLINE
    - TEST=TARGETED
    - TEST=ANNOTATEVEP
    - TEST=ANNOTATESNPEFF

before_install:
  # PRs to master are only ok if coming from dev branch
  - '[ $TRAVIS_PULL_REQUEST = "false" ] || [ $TRAVIS_BRANCH != "master" ] || ([ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ] && [ $TRAVIS_PULL_REQUEST_BRANCH = "dev" ])'
  # Pull the docker image first so the test doesn't wait for this
  - "travis_retry ./scripts/download_docker.sh --test $TEST"

install:
  # Install Nextflow
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Reset
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests

# Build references if needed
before_script:
  - "${TRAVIS_BUILD_DIR}/scripts/build_reference.sh --test $TEST --verbose"

# Actual tests
script:
  - "${TRAVIS_BUILD_DIR}/scripts/run_tests.sh --test $TEST --verbose"
