name: strelka_somatic
description: Strelka2 is a fast and accurate small variant caller optimized for analysis of somatic variation
keywords:
  - variantcalling
  - somatic
  - wgs
  - vcf
  - variants
tools:
  - strelka:
      description: Strelka calls somatic and germline small variants from mapped sequencing reads
      homepage: https://github.com/Illumina/strelka
      documentation: https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md
      tool_dev_url: https://github.com/Illumina/strelka
      doi: 10.1038/s41592-018-0051-x
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test']
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam}"
  - bai:
      type: file
      description: BAM index file
      pattern: "*.{bai}"
  - target_bed:
      type: file
      description: An optional bed file
      pattern: "*.{bed}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test']
  - indels_vcf:
      type: file
      description: gzipped somatic indels file and associated index file
      pattern: "(*_somatic_indels.vcf.gz, *_somatic_indels.vcf.gz.tbi)"
  - snvs_vcf:
      type: file
      description: gzipped somatic snvs file and associated index file
      pattern: "(*_somatic_snvs.vcf.gz, _somatic_snvs.vcf.gz.tbi)"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@arontommi"
