name: "snpsift_annmemcreate"
description: |
  Create memory-optimized SnpSift vardb databases from VCF files for use with SnpSift annMem annotation.
  Converts VCF files (e.g. ClinVar, dbSNP, Cosmic) into indexed dataframes for fast lookup.
keywords:
  - vcf
  - annotation
  - snpsift
  - variant
  - database
tools:
  - snpsift:
      description: "Genetic variant annotations and functional effect prediction toolbox"
      homepage: "https://pcingola.github.io/SnpEff/snpsift/annotate_mem/"
      documentation: "https://pcingola.github.io/SnpEff/snpsift/annotate_mem/"
      tool_dev_url: "https://github.com/pcingola/SnpSift"
      doi: "10.3389/fgene.2012.00035"
      licence:
        - "MIT"
      identifier: biotools:snpsift
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test' ]`
    - db_vcf:
        type: file
        description: VCF file to build the database from
        pattern: "*.{vcf,vcf.gz}"
        ontologies: []
    - db_vcf_tbi:
        type: file
        description: Tabix index for the database VCF file (optional)
        pattern: "*.tbi"
        ontologies: []
    - db_fields:
        type: list
        description: |
          INFO field names to include in the database.
          Can be a list or a single string.
output:
  database:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test' ]`
      - "*.snpsift.vardb":
          type: directory
          description: SnpSift vardb directory containing indexed dataframes
          pattern: "*.snpsift.vardb"
  versions_snpsift:
    - - ${task.process}:
          type: string
          description: The name of the process
      - snpsift:
          type: string
          description: The name of the tool
      - SnpSift -version 2>&1 | grep -oE '[0-9]+\.[0-9]+[a-z]?':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - snpsift:
          type: string
          description: The tool name
      - SnpSift -version 2>&1 | grep -oE '[0-9]+\.[0-9]+[a-z]?':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@friederike-hanssen"
maintainers:
  - "@friederike-hanssen"
