name: snpeff_download
description: Genetic variant annotation and functional effect prediction toolbox
keywords:
  - annotation
  - effect prediction
  - snpeff
  - variant
  - vcf
tools:
  - snpeff:
      description: |
        SnpEff is a variant annotation and effect prediction tool.
        It annotates and predicts the effects of genetic variants on genes and proteins (such as amino acid changes).
      homepage: https://pcingola.github.io/SnpEff/
      documentation: https://pcingola.github.io/SnpEff/se_introduction/
      licence: ["MIT"]
      identifier: biotools:snpeff
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - genome:
        type: file
        description: Reference genome in FASTA format
        pattern: "*.{fasta,fna,fa}"
    - cache_version:
        type: string
        description: Version of the snpEff cache to download
output:
  - cache:
      - meta:
          type: file
          description: |
            snpEff cache
      - snpeff_cache:
          type: file
          description: |
            snpEff cache
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@maxulysse"
maintainers:
  - "@maxulysse"
