name: fgbio_fastqtobam
description: |
  Using the fgbio tools, converts FASTQ files sequenced into unaligned BAM or CRAM files possibly moving the UMI barcode into the RX field of the reads
keywords:
  - fastqtobam
  - fgbio
tools:
  - fgbio:
      description: A set of tools for working with genomic and high throughput sequencing data, including UMIs
      homepage: http://fulcrumgenomics.github.io/fgbio/
      documentation: http://fulcrumgenomics.github.io/fgbio/tools/latest/
      tool_dev_url: https://github.com/fulcrumgenomics/fgbio
      doi: ""
      licence: ["MIT"]

input:
  - reads:
      type: file
      description: pair of reads to be converted into BAM file
      pattern: "*.{fastq.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.yml}"
  - bam:
      type: file
      description: Unaligned, unsorted BAM file
      pattern: "*.{bam}"
  - cram:
      type: file
      description: Unaligned, unsorted CRAM file
      pattern: "*.{cram}"

authors:
  - "@lescai"
  - "@matthdsm"
