name: cnvkit_export
description: Convert copy number ratio tables (.cnr files) or segments (.cns) to another format.
keywords:
  - cnvkit
  - copy number
  - export
tools:
  - cnvkit:
      description: |
        CNVkit is a Python library and command-line software toolkit to infer and visualize copy number from high-throughput DNA sequencing data. It is designed for use with hybrid capture, including both whole-exome and custom target panels, and short-read sequencing platforms such as Illumina and Ion Torrent.
      homepage: https://cnvkit.readthedocs.io/en/stable/index.html
      documentation: https://cnvkit.readthedocs.io/en/stable/index.html
      licence: ["Apache-2.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - cns:
      type: file
      description: CNVKit CNS file.
      pattern: "*.cns"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - cns:
      type: file
      description: File containing copy number segment information
      pattern: "*.{cns}"
authors:
  - "@adamrtalbot"
  - "@priesgo"
maintainers:
  - "@adamrtalbot"
  - "@priesgo"
