name: strelka_somatic
description: Strelka2 is a fast and accurate small variant caller optimized for analysis
  of germline variation in small cohorts and somatic variation in tumor/normal sample
  pairs
keywords:
  - variant calling
  - germline
  - wgs
  - vcf
  - variants
tools:
  - strelka:
      description: Strelka calls somatic and germline small variants from mapped sequencing
        reads
      homepage: https://github.com/Illumina/strelka
      documentation: https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md
      tool_dev_url: https://github.com/Illumina/strelka
      doi: 10.1038/s41592-018-0051-x
      licence: ["GPL v3"]
      identifier: biotools:strelka
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input_normal:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies: []
    - input_index_normal:
        type: file
        description: BAM/CRAM/SAM index file
        pattern: "*.{bai,crai,sai}"
        ontologies: []
    - input_tumor:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies: []
    - input_index_tumor:
        type: file
        description: BAM/CRAM/SAM index file
        pattern: "*.{bai,crai,sai}"
        ontologies: []
    - manta_candidate_small_indels:
        type: file
        description: VCF.gz file
        pattern: "*.{vcf.gz}"
        ontologies: []
    - manta_candidate_small_indels_tbi:
        type: file
        description: VCF.gz index file
        pattern: "*.tbi"
        ontologies: []
    - target_bed:
        type: file
        description: BED file containing target regions for variant calling
        pattern: "*.{bed}"
        ontologies: []
    - target_bed_index:
        type: file
        description: Index for BED file containing target regions for variant calling
        pattern: "*.{bed.tbi}"
        ontologies: []
  - fasta:
      type: file
      description: Genome reference FASTA file
      pattern: "*.{fa,fasta}"
      ontologies: []
  - fai:
      type: file
      description: Genome reference FASTA index file
      pattern: "*.{fa.fai,fasta.fai}"
      ontologies: []
output:
  vcf_indels:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.somatic_indels.vcf.gz":
          type: file
          description: Gzipped VCF file containing variants
          pattern: "*.{vcf.gz}"
          ontologies: []
  vcf_indels_tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.somatic_indels.vcf.gz.tbi":
          type: file
          description: Index for gzipped VCF file containing variants
          pattern: "*.{vcf.gz.tbi}"
          ontologies: []
  vcf_snvs:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.somatic_snvs.vcf.gz":
          type: file
          description: Gzipped VCF file containing variants
          pattern: "*.{vcf.gz}"
          ontologies: []
  vcf_snvs_tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.somatic_snvs.vcf.gz.tbi":
          type: file
          description: Index for gzipped VCF file containing variants
          pattern: "*.{vcf.gz.tbi}"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@drpatelh"
maintainers:
  - "@drpatelh"
