name: yte
description: A YAML template engine with Python expressions
keywords:
  - yaml
  - template
  - python
tools:
  - yte:
      description: "A YAML template engine with Python expressions"
      homepage: "https://yte-template-engine.github.io/"
      documentation: "https://yte-template-engine.github.io/"
      tool_dev_url: "https://github.com/yte-template-engine/yte"
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'template1' ]`
    - template:
        type: file
        description: YTE template
        pattern: "*.{yaml}"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
  - map_file:
      type: file
      description: YAML file containing a map to be used in the template
      pattern: "*.{yaml}"
      ontologies:
        - edam: http://edamontology.org/format_3750 # YAML
  - map:
      type: map
      description: |
        Groovy Map containing mapping information to be used in the template
        e.g. `[ key: value ]` with key being a wildcard in the template

output:
  rendered:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.yaml":
          type: file
          description: Rendered YAML file
          pattern: "*.yaml"
          ontologies:
            - edam: http://edamontology.org/format_3750 # YAML
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML

authors:
  - "@famosab"
maintainers:
  - "@famosab"
