name: sentieon_haplotyper
description: Runs Sentieon's haplotyper for germline variant calling.
keywords:
  - sentieon
  - haplotypecaller
  - haplotype
tools:
  - sentieon:
      description: |
        Sentieon® provides complete solutions for secondary DNA/RNA analysis for a variety of sequencing platforms, including short and long reads.
        Our software improves upon BWA, STAR, Minimap2, GATK, HaplotypeCaller, Mutect, and Mutect2 based pipelines and is deployable on any generic-CPU-based computing system.
      homepage: https://www.sentieon.com/
      documentation: https://www.sentieon.com/
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM file from alignment
        pattern: "*.{bam,cram}"
    - input_index:
        type: file
        description: BAI/CRAI file from alignment
        pattern: "*.{bai,crai}"
    - intervals:
        type: file
        description: Bed file with the genomic regions included in the library (optional)
    - recal_table:
        type: file
        description: Recalibration table from sentieon/qualcal (optional)
  - - meta1:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Genome fasta file
        pattern: "*.{fa,fasta}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: The index of the FASTA reference.
        pattern: "*.fai"
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - dbsnp:
        type: file
        description: VCF file containing known sites (optional)
  - - meta4:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - dbsnp_tbi:
        type: file
        description: VCF index of dbsnp (optional)
  - - emit_vcf:
        type: string
        description: |
          Controls the vcf output from the haplotyper.
          If emit_vcf is set to "all" then the haplotyper will output a vcf generated by the haplotyper in emit-mode "all".
          If emit_vcf is set to "confident" then the haplotyper will output a vcf generated by the haplotyper in emit-mode "confident".
          If emit_vcf is set to "variant" then the haplotyper will output a vcf generated by the haplotyper in emit_mode "confident".
  - - emit_gvcf:
        type: boolean
        description: If true, the haplotyper will output a gvcf
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
      - "*.unfiltered.vcf.gz":
          type: file
          description: Compressed VCF file
          pattern: "*.unfiltered.vcf.gz"
  - vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
      - "*.unfiltered.vcf.gz.tbi":
          type: file
          description: Index of VCF file
          pattern: "*.unfiltered.vcf.gz.tbi"
  - gvcf:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
      - "*.g.vcf.gz":
          type: file
          description: Compressed GVCF file
          pattern: "*.g.vcf.gz"
  - gvcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
      - "*.g.vcf.gz.tbi":
          type: file
          description: Index of GVCF file
          pattern: "*.g.vcf.gz.tbi"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@asp8200"
maintainers:
  - "@asp8200"
