---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::cnvkit=0.9.10
  - bioconda::htslib=1.17
  - bioconda::samtools=1.17
