name: cnvkit_batch
description: Copy number variant detection from high-throughput sequencing data
keywords:
  - cnvkit
  - bam
  - fasta
  - copy number
tools:
  - cnvkit:
      description: |
        CNVkit is a Python library and command-line software toolkit to infer and visualize copy number from high-throughput DNA sequencing data. It is designed for use with hybrid capture, including both whole-exome and custom target panels, and short-read sequencing platforms such as Illumina and Ion Torrent.
      homepage: https://cnvkit.readthedocs.io/en/stable/index.html
      documentation: https://cnvkit.readthedocs.io/en/stable/index.html
      licence: ["Apache-2.0"]
      identifier: biotools:cnvkit
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - tumor:
        type: file
        description: |
          Input tumour sample bam file (or cram)
    - normal:
        type: file
        description: |
          Input normal sample bam file (or cram)
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test' ]
    - fasta:
        type: file
        description: |
          Input reference genome fasta file (only needed for cram_input and/or when normal_samples are provided)
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test' ]
    - fasta_fai:
        type: file
        description: |
          Input reference genome fasta index (optional, but recommended for cram_input)
  - - meta4:
        type: map
        description: |
          Groovy Map containing information about target file
          e.g. [ id:'test' ]
    - targets:
        type: file
        description: |
          Input target bed file
  - - meta5:
        type: map
        description: |
          Groovy Map containing information about reference file
          e.g. [ id:'test' ]
    - reference:
        type: file
        description: |
          Input reference cnn-file (only for germline and tumor-only running)
  - - panel_of_normals:
        type: file
        description: |
          Input panel of normals file
output:
  - bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bed":
          type: file
          description: File containing genomic regions
          pattern: "*.{bed}"
  - cnn:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cnn":
          type: file
          description: File containing coverage information
          pattern: "*.{cnn}"
  - cnr:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cnr":
          type: file
          description: File containing copy number ratio information
          pattern: "*.{cnr}"
  - cns:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cns":
          type: file
          description: File containing copy number segment information
          pattern: "*.{cns}"
  - pdf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.pdf":
          type: file
          description: File with plot of copy numbers or segments on chromosomes
          pattern: "*.{pdf}"
  - png:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.png":
          type: file
          description: File with plot of bin-level log2 coverages and segmentation calls
          pattern: "*.{png}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@adamrtalbot"
  - "@drpatelh"
  - "@fbdtemme"
  - "@kaurravneet4123"
  - "@KevinMenden"
  - "@lassefolkersen"
  - "@MaxUlysse"
  - "@priesgo"
  - "@SusiJo"
maintainers:
  - "@adamrtalbot"
  - "@drpatelh"
  - "@fbdtemme"
  - "@kaurravneet4123"
  - "@KevinMenden"
  - "@lassefolkersen"
  - "@MaxUlysse"
  - "@priesgo"
  - "@SusiJo"
