# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fastq_align_parabricks"
description: Align a fastq file using GPU-based acceleration
keywords:
  - fastq
  - align
  - parabricks
  - gpu
  - preprocessing
components:
  - parabricks/fq2bam
  - parabricks/applybqsr
input:
  - ch_reads:
      type: file
      description: |
        Channel containing reads (either one file for se or two files for pe)
        Structure: [ val(meta), [ path(fastq1), path(fastq2) ] ]
  - ch_fasta:
      type: file
      description: |
        Channel containing reference fasta file
        Structure: [ val(meta), path(fasta) ]
  - ch_index:
      type: file
      description: |
        Channel containing reference BWA index
        Structure: [ val(meta), path(.{amb,ann,bwt,pac,sa}) ]
  - ch_interval_file:
      type: file
      description: |
        (optional) file(s) containing genomic intervals for use in base
        quality score recalibration (BQSR)
        Structure: [ val(meta), path(.{bed,interval_list,picard,list,intervals}) ]
  - ch_known_sites:
      type: file
      description: |
        (optional) known sites file(s) for calculating BQSR. markdups must
        be true to perform BQSR.
        Structure [ path(vcf) ]
output:
  - bam:
      type: file
      description: |
        Channel containing BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: file
      description: |
        Channel containing indexed BAM (BAI) files
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@famosab"
maintainers:
  - "@famosab"
