name: samtools_convert
description: convert and then index CRAM -> BAM or BAM -> CRAM file
keywords:
  - view
  - index
  - bam
  - cram
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: hhttp://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input:
      type: file
      description: BAM/CRAM file
      pattern: "*.{bam,cram}"
  - index:
      type: file
      description: BAM/CRAM index file
      pattern: "*.{bai,crai}"
  - fasta:
      type: file
      description: Reference file to create the CRAM file
      pattern: "*.{fasta,fa}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - alignment_index:
      type: file
      description: filtered/converted BAM/CRAM file + index
      pattern: "*{.bam/cram,.bai/crai}"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
authors:
  - "@FriederikeHanssen"
  - "@maxulysse"
