---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  # renovate: datasource=conda depName=bioconda/bwa
  - bioconda::bwa=0.7.18
  # renovate: datasource=conda depName=bioconda/htslib
  - bioconda::htslib=1.21
  # renovate: datasource=conda depName=bioconda/samtools
  - bioconda::samtools=1.21
