name: bcftools_index
description: Index VCF tools
keywords:
  - vcf
  - index
  - bcftools
  - csi
  - tbi
tools:
  - bcftools:
      description: BCFtools is a set of utilities that manipulate variant calls in the
        Variant Call Format (VCF) and its binary counterpart BCF. All commands work
        transparently with both VCFs and BCFs, both uncompressed and BGZF-compressed.  Most
        commands accept VCF, bgzipped VCF and BCF with filetype detected automatically
        even when streaming from a pipe. Indexed VCF and BCF will work in all situations.
        Un-indexed VCF and BCF and streams will work in most, but not all situations.
      homepage: https://samtools.github.io/bcftools/
      documentation: https://samtools.github.io/bcftools/howtos/index.html
      tool_dev_url: https://github.com/samtools/bcftools
      doi: "10.1093/gigascience/giab008"
      licence: ["MIT", "GPL-3.0-or-later"]
      identifier: biotools:bcftools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - vcf:
        type: file
        description: VCF file (optionally GZIPPED)
        pattern: "*.{vcf,vcf.gz}"
output:
  - csi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csi":
          type: file
          description: Default VCF file index file
          pattern: "*.csi"
  - tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tbi":
          type: file
          description: Alternative VCF file index file for larger files (activated with
            -t parameter)
          pattern: "*.tbi"
  - versions:
      - versions.yml:
          type: file
          description: File containing software version
          pattern: "versions.yml"
authors:
  - "@jfy133"
maintainers:
  - "@jfy133"
