name: "fastq_align_dna"
description: Align fastq files to a reference genome
keywords:
  - fastq
  - bam
  - sort
  - bwamem
  - bwamem2
  - dragmap
  - snapaligner
modules:
  - bowtie2/align
  - bwa/mem
  - bwamem2/mem
  - dragmap/align
  - snapaligner/align
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ id:'test' ]
  - index:
      type: file
      description: Aligner genome index files
      pattern: "Directory containing aligner index"
  - aligner:
      type: string
      description: Aligner to use for alignment
      enum:
        - bowtie2
        - bwa
        - bwamem2
        - dragmap
        - snap
  - sort_bam:
      type: boolean
      description: sort output
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - bam:
      type: file
      description: BAM file
      pattern: "*.bam"
  - bai:
      type: file
      description: BAM index (currently only for snapaligner)
      pattern: "*.bai"
  - report:
      type: file
      description: Alignment report (currently only for dragmap)
      pattern: "*.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@matthdsm"
