name: bcftools_sort
description: Sorts VCF files
keywords:
  - sorting
  - VCF
  - variant calling
tools:
  - sort:
      description: Sort VCF files by coordinates.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      tool_dev_url: https://github.com/samtools/bcftools
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]
      identifier: biotools:bcftools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - vcf:
        type: file
        description: The VCF/BCF file to be sorted
        pattern: "*.{vcf.gz,vcf,bcf}"
        ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.{vcf,vcf.gz,bcf,bcf.gz}":
          type: file
          description: Sorted VCF file
          pattern: "*.{vcf.gz}"
          ontologies: []
  tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tbi":
          type: file
          description: Alternative VCF file index
          pattern: "*.tbi"
          ontologies: []
  csi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csi":
          type: file
          description: Default VCF file index
          pattern: "*.csi"
          ontologies: []
  versions_bcftools:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bcftools:
          type: string
          description: The tool name
      - "bcftools --version | sed '1!d; s/^.*bcftools //'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bcftools:
          type: string
          description: The tool name
      - "bcftools --version | sed '1!d; s/^.*bcftools //'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@Gwennid"
maintainers:
  - "@Gwennid"
