version: 2.0
jobs:
  snpeffgrch37:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      GENOME: GRCh37
      SNPEFF_CACHE_VERSION: 75
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t nfcore/sareksnpeff:dev.${GENOME} containers/snpeff/. --build-arg GENOME=${GENOME} --build-arg SNPEFF_CACHE_VERSION=${SNPEFF_CACHE_VERSION}
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push nfcore/sareksnpeff:dev.${GENOME}

  snpeffgrch38:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      GENOME: GRCh38
      SNPEFF_CACHE_VERSION: 86
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t nfcore/sareksnpeff:dev.${GENOME} containers/snpeff/. --build-arg GENOME=${GENOME} --build-arg SNPEFF_CACHE_VERSION=${SNPEFF_CACHE_VERSION}
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push nfcore/sareksnpeff:dev.${GENOME}

  snpeffgrcm38:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      GENOME: GRCm38
      SNPEFF_CACHE_VERSION: 86
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t nfcore/sareksnpeff:dev.${GENOME} containers/snpeff/. --build-arg GENOME=${GENOME} --build-arg SNPEFF_CACHE_VERSION=${SNPEFF_CACHE_VERSION}
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push nfcore/sareksnpeff:dev.${GENOME}

  vepgrch37:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      GENOME: GRCh37
      SPECIES: homo_sapiens
      VEP_VERSION: 95
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t nfcore/sarekvep:dev.${GENOME} containers/vep/. --build-arg GENOME=${GENOME} --build-arg SPECIES=${SPECIES} --build-arg VEP_VERSION=${VEP_VERSION}
          no_output_timeout: 1.5h
      - run:
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sarekvep:dev.${GENOME}

  vepgrch38:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      GENOME: GRCh38
      SPECIES: homo_sapiens
      VEP_VERSION: 95
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t nfcore/sarekvep:dev.${GENOME} containers/vep/. --build-arg GENOME=${GENOME} --build-arg SPECIES=${SPECIES} --build-arg VEP_VERSION=${VEP_VERSION}
          no_output_timeout: 1.5h
      - run:
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sarekvep:dev.${GENOME}

  vepgrcm38:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      GENOME: GRCm38
      SPECIES: mus_musculus
      VEP_VERSION: 95
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: docker build -t nfcore/sarekvep:dev.${GENOME} containers/vep/. --build-arg GENOME=${GENOME} --build-arg SPECIES=${SPECIES} --build-arg VEP_VERSION=${VEP_VERSION}
          no_output_timeout: 30m
      - run:
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sarekvep:dev.${GENOME}

workflows:
  version: 2
  build:
    jobs:
      - snpeffgrch37
      - snpeffgrch38
      - snpeffgrcm38
      - vepgrch37
      - vepgrch38
      - vepgrcm38
