version: 2.1
jobs:
  buildsnpeffgrch37:
    machine: true
    environment:
      GENOME: GRCh37
      SNPEFF_CACHE_VERSION: 75
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t nfcore/sareksnpeff:dev.${GENOME} containers/snpeff/. --build-arg GENOME=${GENOME} --build-arg SNPEFF_CACHE_VERSION=${SNPEFF_CACHE_VERSION}
      - run:
          name: Push Docker Image to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sareksnpeff:dev.${GENOME}

  buildsnpeffgrch38:
    machine: true
    environment:
      GENOME: GRCh38
      SNPEFF_CACHE_VERSION: 86
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t nfcore/sareksnpeff:dev.${GENOME} containers/snpeff/. --build-arg GENOME=${GENOME} --build-arg SNPEFF_CACHE_VERSION=${SNPEFF_CACHE_VERSION}
      - run:
          name: Push Docker Image to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sareksnpeff:dev.${GENOME}

  buildsnpeffgrcm38:
    machine: true
    environment:
      GENOME: GRCm38
      SNPEFF_CACHE_VERSION: 86
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t nfcore/sareksnpeff:dev.${GENOME} containers/snpeff/. --build-arg GENOME=${GENOME} --build-arg SNPEFF_CACHE_VERSION=${SNPEFF_CACHE_VERSION}
      - run:
          name: Push Docker Image to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sareksnpeff:dev.${GENOME}

  buildvepgrch37:
    machine: true
    environment:
      GENOME: GRCh37
      SPECIES: homo_sapiens
      VEP_VERSION: 95
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t nfcore/sarekvep:dev.${GENOME} containers/vep/. --build-arg GENOME=${GENOME} --build-arg SPECIES=${SPECIES} --build-arg VEP_VERSION=${VEP_VERSION}
      - run:
          name: Push Docker Image to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sarekvep:dev.${GENOME}
          no_output_timeout: 2h

  buildvepgrch38:
    machine: true
    environment:
      GENOME: GRCh38
      SPECIES: homo_sapiens
      VEP_VERSION: 95
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t nfcore/sarekvep:dev.${GENOME} containers/vep/. --build-arg GENOME=${GENOME} --build-arg SPECIES=${SPECIES} --build-arg VEP_VERSION=${VEP_VERSION}
      - run:
          name: Push Docker Image to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sarekvep:dev.${GENOME}
          no_output_timeout: 2h

  buildvepgrcm38:
    machine: true
    environment:
      GENOME: GRCm38
      SPECIES: mus_musculus
      VEP_VERSION: 95
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t nfcore/sarekvep:dev.${GENOME} containers/vep/. --build-arg GENOME=${GENOME} --build-arg SPECIES=${SPECIES} --build-arg VEP_VERSION=${VEP_VERSION}
      - run:
          name: Push Docker Image to DockerHub
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin ; docker push nfcore/sarekvep:dev.${GENOME}
          no_output_timeout: 2h

workflows:
  version: 2
  build:
    jobs:
      - buildsnpeffgrch37
      - buildsnpeffgrch38
      - buildsnpeffgrcm38
      - buildvepgrch37
      - buildvepgrch38
      - buildvepgrcm38
