name: cnvkit_batch
description: Copy number variant detection from high-throughput sequencing data
keywords:
  - bam
  - fasta
  - copy number
tools:
  - cnvkit:
      description: |
        CNVkit is a Python library and command-line software toolkit to infer and visualize copy number from high-throughput DNA sequencing data. It is designed for use with hybrid capture, including both whole-exome and custom target panels, and short-read sequencing platforms such as Illumina and Ion Torrent.
      homepage: https://cnvkit.readthedocs.io/en/stable/index.html
      documentation: https://cnvkit.readthedocs.io/en/stable/index.html
      licence: ["Apache-2.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tumour:
      type: file
      description: |
        Input tumour sample bam file (or cram)
  - normal:
      type: file
      description: |
        Input normal sample bam file (or cram)
  - fasta:
      type: file
      description: |
        Input reference genome fasta file (only needed for cram_input and/or when normal_samples are provided)
  - fasta_fai:
      type: file
      description: |
        Input reference genome fasta index (optional, but recommended for cram_input)
  - targetfile:
      type: file
      description: |
        Input target bed file
  - reference:
      type: file
      description: |
        Input reference cnn-file (only for germline and tumor-only running)
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: File containing genomic regions
      pattern: "*.{bed}"
  - cnn:
      type: file
      description: File containing coverage information
      pattern: "*.{cnn}"
  - cnr:
      type: file
      description: File containing copy number ratio information
      pattern: "*.{cnr}"
  - cns:
      type: file
      description: File containing copy number segment information
      pattern: "*.{cns}"
  - pdf:
      type: file
      description: File with plot of copy numbers or segments on chromosomes
      pattern: "*.{pdf}"
  - png:
      type: file
      description: File with plot of bin-level log2 coverages and segmentation calls
      pattern: "*.{png}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kaurravneet4123"
  - "@KevinMenden"
  - "@MaxUlysse"
  - "@drpatelh"
  - "@fbdtemme"
  - "@lassefolkersen"
  - "@SusiJo"
