name: deepvariant
description: DeepVariant is an analysis pipeline that uses a deep neural network to call genetic variants from next-generation DNA sequencing data
keywords:
  - variant calling
  - machine learning
tools:
  - deepvariant:
      description: DeepVariant is an analysis pipeline that uses a deep neural network to call genetic variants from next-generation DNA sequencing data
      homepage: https://github.com/google/deepvariant
      documentation: https://github.com/google/deepvariant
      tool_dev_url: https://github.com/google/deepvariant
      doi: "https://doi.org/10.1038/nbt.4235"
      licence: ["BSD-3-clause"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - input:
      type: file
      description: BAM/CRAM file
      pattern: "*.bam/cram"
  - index:
      type: file
      description: Index of BAM/CRAM file
      pattern: "*.bai/crai"
  - interval:
      type: file
      description: Interval file for targeted regions
      pattern: "*.bed"
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fai"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: Compressed VCF file
      pattern: "*.vcf.gz"
  - gvcf:
      type: file
      description: Compressed GVCF file
      pattern: "*.g.vcf.gz"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@abhi18av"
