name: gatk4_gatherbqsrreports
description: Gathers scattered BQSR recalibration reports into a single file
keywords:
  - base quality score recalibration
  - bqsr
  - gatherbqsrreports
  - gatk4
tools:
  - gatk4:
      description: Genome Analysis Toolkit (GATK4)
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us
      tool_dev_url: https://github.com/broadinstitute/gatk
      doi: "10.1158/1538-7445.AM2017-3590"
      licence: ["BSD-3-clause"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - table:
        type: file
        description: File(s) containing BQSR table(s)
        pattern: "*.table"
output:
  - table:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.table":
          type: file
          description: File containing joined BQSR table
          pattern: "*.table"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@FriederikeHanssen"
maintainers:
  - "@FriederikeHanssen"
