---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  # renovate: datasource=conda depName=bioconda/ensembl-vep
  - bioconda::ensembl-vep=116.0
  # renovate: datasource=conda depName=bioconda/perl-math-cdf
  - bioconda::perl-math-cdf=0.1
  # renovate: datasource=conda depName=bioconda/htslib
  - bioconda::htslib=1.23.1
