name: bwamem2_mem
description: Performs fastq alignment to a fasta reference using BWA
keywords:
  - mem
  - bwa
  - alignment
  - map
  - fastq
  - bam
  - sam
tools:
  - bwamem2:
      description: |
        BWA-mem2 is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: https://github.com/bwa-mem2/bwa-mem2
      documentation: https://github.com/bwa-mem2/bwa-mem2#usage
      doi: "10.1109/IPDPS.2019.00041"
      publication:
        author: "Vasimuddin M., Misra S., Li H. & Aluru S."
        year: 2018
        source: "IEEE International Parallel and Distributed Processing Symposium (IPDPS)"
        title: "Efficient Architecture-Aware Acceleration of BWA-MEM for Multicore Systems"
      licence:
        - "MIT"
      identifier: "biotools:bwa-mem2"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies:
          - edam: "http://edamontology.org/data_2044"
          - edam: "http://edamontology.org/format_1930"
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference/index information
          e.g. [ id:'test' ]
    - index:
        type: file
        description: BWA genome index files
        pattern: "Directory containing BWA index *.{0132,amb,ann,bwt.2bit.64,pac}"
        ontologies:
          - edam: "http://edamontology.org/data_3210"
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: Reference genome in FASTA format
        pattern: "*.{fa,fasta,fna}"
        ontologies:
          - edam: "http://edamontology.org/data_2044"
          - edam: "http://edamontology.org/format_1929"
  - sort_bam:
      type: boolean
      description: use samtools sort (true) or samtools view (false)
      pattern: "true or false"
output:
  sam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sam":
          type: file
          description: Output SAM file containing read alignments
          pattern: "*.{sam}"
          ontologies:
            - edam: "http://edamontology.org/format_2573"
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bam":
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572"
  cram:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cram":
          type: file
          description: Output CRAM file containing read alignments
          pattern: "*.{cram}"
          ontologies:
            - edam: "http://edamontology.org/format_3462"
  crai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.crai":
          type: file
          description: Index file for CRAM file
          pattern: "*.{crai}"
          ontologies: []
  csi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csi":
          type: file
          description: Index file for BAM file
          pattern: "*.{csi}"
          ontologies: []
  versions_bwamem2:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bwamem2:
          type: string
          description: The name of the tool
      - bwa-mem2 version | grep -o -E "[0-9]+(\.[0-9]+)+":
          type: eval
          description: The expression to obtain the version of the tool
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bwamem2:
          type: string
          description: The name of the tool
      - bwa-mem2 version | grep -o -E "[0-9]+(\.[0-9]+)+":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@maxulysse"
  - "@matthdsm"
maintainers:
  - "@maxulysse"
  - "@matthdsm"
