name: deepvariant_rundeepvariant
description: DeepVariant is an analysis pipeline that uses a deep neural network to
  call genetic variants from next-generation DNA sequencing data
keywords:
  - variant calling
  - machine learning
  - neural network
tools:
  - deepvariant:
      description: DeepVariant is an analysis pipeline that uses a deep neural network
        to call genetic variants from next-generation DNA sequencing data
      homepage: https://github.com/google/deepvariant
      documentation: https://github.com/google/deepvariant
      tool_dev_url: https://github.com/google/deepvariant
      doi: "10.1038/nbt.4235"
      licence: ["BSD-3-clause"]
      identifier: biotools:deepvariant
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM file
        pattern: "*.bam/cram"
        ontologies: []
    - index:
        type: file
        description: Index of BAM/CRAM file
        pattern: "*.bai/crai"
        ontologies: []
    - intervals:
        type: file
        description: file containing intervals
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.fasta"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fai:
        type: file
        description: Index of reference fasta file
        pattern: "*.fai"
        ontologies: []
  - - meta4:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - gzi:
        type: file
        description: GZI index of reference fasta file
        pattern: "*.gzi"
        ontologies: []
  - - meta5:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - par_bed:
        type: file
        description: BED file containing PAR regions
        pattern: "*.bed"
        ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.vcf.gz:
          type: file
          description: Compressed VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  vcf_index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.vcf.gz.{tbi,csi}:
          type: file
          description: Tabix index file of compressed VCF
          pattern: "*.vcf.gz.{tbi,csi}"
          ontologies: []
  gvcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.g.vcf.gz:
          type: file
          description: Compressed GVCF file
          pattern: "*.g.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  gvcf_index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.g.vcf.gz.{tbi,csi}:
          type: file
          description: Tabix index file of compressed GVCF
          pattern: "*.g.vcf.gz.{tbi,csi}"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@abhi18av"
  - "@ramprasadn"
maintainers:
  - "@abhi18av"
  - "@ramprasadn"
