Bootstrap: docker
From: ubuntu:latest

%labels
  MAINTAINER "Szilveszter Juhos"

%environment
  SAREK_BASE=/opt/sarek
  export SAREK_BASE

%runscript

  echo "I can put here whatever I want to happen when the user runs my container!"
  exec echo "Hello Monsoir Meatball" "$@"

%post
 
  echo "Here we are installing software and other dependencies for the container!"
  mkdir -p /opt/sarek
  apt-get update
  apt-get install -y git bash vim
  echo "echo \"Eljen II Rakoczi Feco!\" "  > /opr/sarek/test.sh
  chmod 755 /opt/sarek/test.sh


%runscript
  echo "This gets run when you run the image!" 
  exec /bin/bash ${SAREK_BASE}/test.sh "$@"  

