---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  # renovate: datasource=conda depName=bioconda/bwa-mem2
  - bwa-mem2=2.2.1
  # renovate: datasource=conda depName=bioconda/htslib
  - htslib=1.21
  # renovate: datasource=conda depName=bioconda/samtools
  - samtools=1.21
