name: bwamem2_index
description: Create BWA-mem2 index for reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - bwamem2:
      description: |
        BWA-mem2 is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: https://github.com/bwa-mem2/bwa-mem2
      documentation: https://github.com/bwa-mem2/bwa-mem2#usage
      licence: ["MIT"]
      identifier: "biotools:bwa-mem2"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
        ontologies:
          - edam: "http://edamontology.org/data_2044" # Sequence
          - edam: "http://edamontology.org/format_1929" # FASTA
output:
  index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - bwamem2:
          type: file
          description: BWA genome index files
          pattern: "*.{0123,amb,ann,bwt.2bit.64,pac}"
          ontologies:
            - edam: "http://edamontology.org/data_3210" # Genome index
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@maxulysse"
maintainers:
  - "@maxulysse"
