# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "goleft_indexcov"
description: Quickly estimate coverage from a whole-genome bam or cram index. A bam
  index has 16KB resolution so that's what this gives, but it provides what appears
  to be a high-quality coverage estimate in seconds per genome.
keywords:
  - coverage
  - cnv
  - genomics
  - depth
tools:
  - "goleft":
      description: "goleft is a collection of bioinformatics tools distributed under
        MIT license in a single static binary"
      homepage: "https://github.com/brentp/goleft"
      documentation: "https://github.com/brentp/goleft"
      tool_dev_url: "https://github.com/brentp/goleft"
      doi: "10.1093/gigascience/gix090"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false]
    - bams:
        type: file
        description: Sorted BAM/CRAM/SAM files
        pattern: "*.{bam,cram,sam}"
    - indexes:
        type: file
        description: BAI/CRAI files
        pattern: "*.{bai,crai}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false]
    - fai:
        type: file
        description: FASTA index
        pattern: "*.{fai}"
output:
  - output:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/*:
          type: file
          description: Files generated by indexcov
  - ped:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/*ped:
          type: file
          description: ped files
          pattern: "*ped"
  - bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/*bed.gz:
          type: file
          description: bed files
          pattern: "*bed.gz"
  - bed_index:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/*bed.gz.tbi:
          type: file
          description: bed index files
          pattern: "*bed.gz.tbi"
  - roc:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/*roc:
          type: file
          description: roc files
          pattern: "*roc"
  - html:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/*html:
          type: file
          description: html files
          pattern: "*html"
  - png:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}/*png:
          type: file
          description: png files
          pattern: "*png"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@lindenb"
maintainers:
  - "@lindenb"
