name: dragmap_hashtable
description: Create DRAGEN hashtable for reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - dragmap:
      description: Dragmap is the Dragen mapper/aligner Open Source Software.
      homepage: https://github.com/Illumina/dragmap
      documentation: https://github.com/Illumina/dragmap
      tool_dev_url: https://github.com/Illumina/dragmap#basic-command-line-usage
      licence: ["GPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
output:
  - hashmap:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information
            e.g. [ id:'test', single_end:false ]
      - dragmap:
          type: file
          description: DRAGMAP hash table
          pattern: "*.{cmp,.bin,.txt}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@edmundmiller"
maintainers:
  - "@edmundmiller"
