name: snpEff
description: Genetic variant annotation and functional effect prediction toolbox
keywords:
  - annotation
tools:
  - snpeff:
      description: |
        SnpEff is a variant annotation and effect prediction tool.
        It annotates and predicts the effects of genetic variants on genes and proteins (such as amino acid changes).
      homepage: https://pcingola.github.io/SnpEff/
      documentation: https://pcingola.github.io/SnpEff/se_introduction/
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: |
        vcf to annotate
  - db:
      type: value
      description: |
        which db to annotate with
  - cache:
      type: file
      description: |
        path to snpEff cache (optional)
output:
  - vcf:
      type: file
      description: |
        annotated vcf
      pattern: "*.ann.vcf"
  - report:
      type: file
      description: snpEff report csv file
      pattern: "*.csv"
  - summary_html:
      type: file
      description: snpEff summary statistics in html file
      pattern: "*.html"
  - genes_txt:
      type: file
      description: txt (tab separated) file having counts of the number of variants affecting each transcript and gene
      pattern: "*.genes.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@maxulysse"
