name: "varlociraptor_preprocess"
description: Obtains per-sample observations for the actual calling process with varlociraptor
  calls
keywords:
  - observations
  - variants
  - preprocessing
tools:
  - "varlociraptor":
      description: |
        Flexible, uncertainty-aware variant calling with parameter free
        filtration via FDR control.
      homepage: "https://varlociraptor.github.io/docs/estimating/"
      documentation: "https://varlociraptor.github.io/docs/calling/"
      tool_dev_url: "https://github.com/varlociraptor/varlociraptor"
      doi: "10.1186/s13059-020-01993-6"
      licence: ["GPL v3"]
      identifier: biotools:varlociraptor
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: http://edamontology.org/format_2572 # BAM
    - bai:
        type: file
        description: Index of the BAM/CRAM/SAM file
        pattern: "*.{bai,crai,sai}"
        ontologies:
          - edam: http://edamontology.org/format_3327 # BAI
    - candidates:
        type: file
        description: Sorted BCF/VCF file
        pattern: "*.{bcf,vcf,vcf.gz}"
        ontologies:
          - edam: http://edamontology.org/format_3016 # VCF
    - alignment_json:
        type: file
        description: File containing alignment properties obtained with varlociraptor/estimatealignmentproperties
        pattern: "*.json"
        ontologies:
          - edam: http://edamontology.org/format_3464 # JSON
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Reference fasta file
        pattern: "*.{fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference index information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: Index for reference fasta file (must be with samtools index)
        pattern: "*.{fai}"
        ontologies: []
output:
  bcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bcf":
          type: file
          description: BCF file containing sample observations
          pattern: "*.bcf"
          ontologies:
            - edam: http://edamontology.org/format_3020 # BCF
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@FriederikeHanssen"
maintainers:
  - "@FriederikeHanssen"
  - "@famosab"
