name: cnvkit_call
description: Given segmented log2 ratio estimates (.cns), derive each segment’s absolute
  integer copy number
keywords:
  - cnvkit
  - bam
  - fasta
  - copy number
tools:
  - cnvkit:
      description: |
        CNVkit is a Python library and command-line software toolkit to infer and visualize copy number from high-throughput DNA sequencing data. It is designed for use with hybrid capture, including both whole-exome and custom target panels, and short-read sequencing platforms such as Illumina and Ion Torrent.
      homepage: https://cnvkit.readthedocs.io/en/stable/index.html
      documentation: https://cnvkit.readthedocs.io/en/stable/index.html
      licence: ["Apache-2.0"]
      identifier: biotools:cnvkit
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - cns:
        type: file
        description: CNVKit CNS file.
        pattern: "*.cns"
    - vcf:
        type: file
        description: Germline VCF file for BAF.
        pattern: "*.vcf{,.gz}"
output:
  - cns:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cns":
          type: file
          description: CNS file.
          pattern: "*.cns"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@adamrtalbot"
  - "@priesgo"
maintainers:
  - "@adamrtalbot"
  - "@priesgo"
