name: "lofreq_somatic"
description: Lofreq subcommand to call low frequency variants from alignments when tumor-normal paired samples are available
keywords:
  - variant calling
  - low frequency variant calling
  - somatic
  - variants
  - vcf
tools:
  - "lofreq":
      description: "A fast and sensitive variant-caller for inferring SNVs and indels from next-generation sequencing data"
      homepage: https://csb5.github.io/lofreq/
      documentation: https://csb5.github.io/lofreq/commands/
      doi: 10.1093/nar/gks918
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: Groovy Map containing sample information e.g. [ id:'test', single_end:false ]
  - meta2:
      type: map
      description: Groovy Map containing reference information
  - meta3:
      type: map
      description: Groovy Map containing reference information
  - tumor:
      type: file
      description: tumor sample input BAM file
      pattern: "*.{bam}"
  - tumor_index:
      type: file
      description: tumor sample BAM index file
      pattern: "*.{bam.bai}"
  - normal:
      type: file
      description: normal sample input BAM file
      pattern: "*.{bam}"
  - normal_index:
      type: file
      description: normal sample BAM index file
      pattern: "*.{bam.bai}"
  - fasta:
      type: file
      description: Reference genome FASTA file
      pattern: "*.{fasta}"
  - fai:
      type: file
      description: Reference genome FASTA index file
      pattern: "*.{fai}"
  - target_bed:
      type: file
      description: BED file containing target regions for variant calling
      pattern: "*.{bed}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf_snvs:
      type: file
      description: Gzipped VCF file containing SNV variants
      pattern: "*.{vcf.gz}"
  - vcf_snvs_tbi:
      type: file
      description: Index for gzipped VCF file containing SNV variants
      pattern: "*.{vcf.gz.tbi}"
  - vcf_indels:
      type: file
      description: Gzipped VCF file containing indels variants
      pattern: "*.{vcf.gz}"
  - vcf_indels.tbi:
      type: file
      description: Index for gzipped VCF file containing indel variants
      pattern: "*.{vcf.gz.tbi}"
authors:
  - "@nevinwu"
maintainers:
  - "@nevinwu"
  - "@AitorPeseta"