name: msisensorpro_scan
description: MSIsensor-pro evaluates Microsatellite Instability (MSI) for cancer patients with next generation sequencing data. It accepts the whole genome sequencing, whole exome sequencing and target region (panel) sequencing data as input
keywords:
  - micro-satellite-scan
  - msisensor-pro
  - scan
tools:
  - msisensorpro:
      description: Microsatellite Instability (MSI) detection using high-throughput sequencing data.
      homepage: https://github.com/xjtu-omics/msisensor-pro
      documentation: https://github.com/xjtu-omics/msisensor-pro/wiki
      tool_dev_url: https://github.com/xjtu-omics/msisensor-pro
      doi: "doi.org/10.1016/j.gpb.2020.02.001"
      licence: ["Custom Licence"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Reference genome
      pattern: "*.{fasta}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - list:
      type: file
      description: File containing microsatellite list
      pattern: "*.{list}"

authors:
  - "@FriederikeHanssen"
