name: tabix_bgziptabix
description: bgzip a sorted tab-delimited genome file and then create tabix
  index
keywords:
  - bgzip
  - compress
  - index
  - tabix
  - vcf
tools:
  - tabix:
      description: Generic indexer for TAB-delimited genome position files.
      homepage: https://www.htslib.org/doc/tabix.html
      documentation: https://www.htslib.org/doc/tabix.1.html
      doi: 10.1093/bioinformatics/btq671
      licence: ["MIT"]
      identifier: biotools:tabix
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: Sorted tab-delimited genome file
        ontologies: []
output:
  gz_index:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.gz":
          type: file
          description: bgzipped tab-delimited genome file
          pattern: "*.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
      - "*.{tbi,csi}":
          type: file
          description: Tabix index file (either tbi or csi)
          pattern: "*.{tbi,csi}"
          ontologies: []
  versions_tabix:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - tabix:
          type: string
          description: The tool name
      - tabix -h 2>&1 | grep -oP 'Version:\s*\K[^\s]+':
          type: eval
          description: The expression to obtain the version of the tool
  versions_bgzip:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bgzip:
          type: string
          description: The tool name
      - bgzip --version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - tabix:
          type: string
          description: The tool name
      - tabix -h 2>&1 | grep -oP 'Version:\s*\K[^\s]+':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - bgzip:
          type: string
          description: The tool name
      - bgzip --version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@maxulysse"
  - "@DLBPointon"
maintainers:
  - "@maxulysse"
  - "@DLBPointon"
