name: "gawk"
description: |
  If you are like many computer users, you would frequently like to make changes in various text files
  wherever certain patterns appear, or extract data from parts of certain lines while discarding the rest.
  The job is easy with awk, especially the GNU implementation gawk.
keywords:
  - gawk
  - awk
  - txt
  - text
  - file parsing
tools:
  - "gawk":
      description: "GNU awk"
      homepage: "https://www.gnu.org/software/gawk/"
      documentation: "https://www.gnu.org/software/gawk/manual/"
      tool_dev_url: "https://www.gnu.org/prep/ftp.html"
      licence: ["GPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: The input file - Specify the logic that needs to be executed on
          this file on the `ext.args2` or in the program file. If the files have a `.gz`
          extension, they will be unzipped using `zcat`.
        pattern: "*"
        ontologies: []
  - program_file:
      type: file
      description: Optional file containing logic for awk to execute. If you don't wish
        to use a file, you can use `ext.args2` to specify the logic.
      pattern: "*"
      ontologies: []
  - disable_redirect_output:
      type: boolean
      description: Disable the redirection of awk output to a given file. This is useful
        if you want to use awk's built-in redirect to write files instead of the shell's
        redirect.
output:
  output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.${suffix}":
          type: file
          description: The output file - if using shell redirection, specify the name
            of this file using `ext.prefix` and the extension using `ext.suffix`. Otherwise,
            ensure the awk program produces files with the extension in `ext.suffix`.
          pattern: "*"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
