name: dragmap_align
description: Performs fastq alignment to a reference using DRAGMAP
keywords:
  - alignment
  - map
  - fastq
  - bam
  - sam
tools:
  - dragmap:
      description: Dragmap is the Dragen mapper/aligner Open Source Software.
      homepage: https://github.com/Illumina/dragmap
      documentation: https://github.com/Illumina/dragmap
      tool_dev_url: https://github.com/Illumina/dragmap#basic-command-line-usage
      licence: ["GPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - hashmap:
        type: file
        description: DRAGMAP hash table
        pattern: "Directory containing DRAGMAP hash table *.{cmp,.bin,.txt}"
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome']
    - fasta:
        type: file
        description: Genome fasta reference files
        pattern: "*.{fa,fasta,fna}"
  - - sort_bam:
        type: boolean
        description: Sort the BAM file
output:
  - sam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.sam":
          type: file
          description: Output SAM file containing read alignments
          pattern: "*.{sam}"
  - bam:
      - meta:
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
      - "*.bam":
          type: file
          description: Output BAM file containing read alignments
          pattern: "*.{bam}"
  - cram:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cram":
          type: file
          description: Output CRAM file containing read alignments
          pattern: "*.{cram}"
  - crai:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.crai":
          type: file
          description: Index file for CRAM file
          pattern: "*.{crai}"
  - csi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csi":
          type: file
          description: Index file for CRAM file
          pattern: "*.{csi}"
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.log":
          type: file
          description: Log file
          pattern: "*.{log}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@edmundmiller"
maintainers:
  - "@edmundmiller"
