name: gatk4_gatherbqsrreports
description: write your description here
keywords:
  - gatk4
  - gatk4_gatherbqsrreports
  - base_recalibration
tools:
  - gatk4:
      description: Genome Analysis Toolkit (GATK4)
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us
      tool_dev_url: https://github.com/broadinstitute/gatk
      doi: "10.1158/1538-7445.AM2017-3590"
      licence: ["BSD-3-clause"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - recal_table:
      type: file
      description: File(s) containing BQSR table(s)
      pattern: "*.table"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - recal_table:
      type: file
      description: File containing joined BQSR table
      pattern: "*.table"

authors:
  - "@FriederikeHanssen"
