name: ensemblvep_download
description: Ensembl Variant Effect Predictor (VEP). The cache downloading
  options are controlled through `task.ext.args`.
keywords:
  - annotation
  - cache
  - download
tools:
  - ensemblvep:
      description: |
        VEP determines the effect of your variants (SNPs, insertions, deletions, CNVs
        or structural variants) on genes, transcripts, and protein sequence, as well as regulatory regions.
      homepage: https://www.ensembl.org/info/docs/tools/vep/index.html
      documentation: https://www.ensembl.org/info/docs/tools/vep/script/index.html
      licence:
        - "Apache-2.0"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - assembly:
        type: string
        description: |
          Genome assembly
    - species:
        type: string
        description: |
          Specie
    - cache_version:
        type: string
        description: |
          cache version
output:
  cache:
    - - meta:
          type: file
          description: cache
          pattern: "*"
          ontologies: []
      - prefix:
          type: file
          description: cache
          pattern: "*"
          ontologies: []
  versions_ensemblvep:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - ensemblvep:
          type: string
          description: The tool name
      - "vep --help | sed -n '/ensembl-vep/s/.*: //p'":
          type: eval
          description: The command used to generate the version of the tool
  versions_perlmathcdf:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - perl-math-cdf:
          type: string
          description: The name of the tool
      - perl -MMath::CDF -e 'print \$Math::CDF::VERSION':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - ensemblvep:
          type: string
          description: The tool name
      - "vep --help | sed -n '/ensembl-vep/s/.*: //p'":
          type: eval
          description: The command used to generate the version of the tool
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - perl-math-cdf:
          type: string
          description: The name of the tool
      - perl -MMath::CDF -e 'print \$Math::CDF::VERSION':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@maxulysse"
maintainers:
  - "@maxulysse"
