name: gatk4_gatherpileupsummaries
description: write your description here
keywords:
  - sort
tools:
  - gatk4:
      description: Genome Analysis Toolkit (GATK4)
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us
      tool_dev_url: https://github.com/broadinstitute/gatk
      doi: "10.1158/1538-7445.AM2017-3590"
      licence: ["BSD-3-clause"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - pileup:
      type: (list of) file(s)
      description: Pileup files from gatk4/getpileupsummaries
      pattern: "*.pileups.table"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - table:
      type: file
      description: Pileup file
      pattern: "*.pileups.table"

authors:
  - "@FriederikeHanssen"
