name: bwa_index
description: Create BWA index for reference genome
keywords:
    - index
    - fasta
    - genome
    - reference
tools:
    - bwa:
        description: |
            BWA is a software package for mapping DNA sequences against
            a large reference genome, such as the human genome.
        homepage: http://bio-bwa.sourceforge.net/
        documentation: http://www.htslib.org/doc/samtools.html
        arxiv: arXiv:1303.3997
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
input:
    - fasta:
        type: file
        description: Input genome fasta file
    - options:
        type: map
        description: |
            Groovy Map containing module options for passing command-line arguments and
            output file paths.
output:
    - index:
        type: file
        description: BWA genome index files
        pattern: "*.{amb,ann,bwt,pac,sa}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@drpatelh"
    - "@maxulysse"
