# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "muse_call"
description: pre-filtering and calculating position-specific summary statistics using
  the Markov substitution model
keywords:
  - variant calling
  - somatic
  - wgs
  - wxs
  - vcf
tools:
  - "MuSE":
      description: "Somatic point mutation caller based on Markov substitution model
        for molecular evolution"
      homepage: "https://bioinformatics.mdanderson.org/public-software/muse/"
      documentation: "https://github.com/wwylab/MuSE"
      tool_dev_url: "https://github.com/wwylab/MuSE"
      doi: "10.1101/gr.278456.123"
      licence: ["https://github.com/danielfan/MuSE/blob/master/LICENSE"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - tumor_bam:
        type: file
        description: Sorted tumor BAM file
        pattern: "*.bam"
        ontologies: []
    - tumor_bai:
        type: file
        description: Index file for the tumor BAM file
        pattern: "*.bai"
        ontologies: []
    - normal_bam:
        type: file
        description: Sorted matched normal BAM file
        pattern: "*.bam"
        ontologies: []
    - normal_bai:
        type: file
        description: Index file for the normal BAM file
        pattern: "*.bai"
        ontologies: []
    - reference:
        type: file
        description: reference genome file
        pattern: ".fasta"
        ontologies: []
output:
  txt:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.MuSE.txt":
          type: file
          description: position-specific summary statistics
          pattern: "*.MuSE.txt"
          ontologies: []
  versions_muse:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - muse:
          type: string
          description: The tool name
      - "MuSE --version | sed -e 's/MuSE, version //g' | sed -e 's/MuSE v//g'":
          type: string
          description: The command used to generate the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - muse:
          type: string
          description: The tool name
      - "MuSE --version | sed -e 's/MuSE, version //g' | sed -e 's/MuSE v//g'":
          type: string
          description: The command used to generate the version of the tool
authors:
  - "@famosab"
maintainers:
  - "@famosab"
