name: gatk_vqsr
description: |
  Recalibrate joint vcf using step1 (VariantRecalibrator) and step2 (applyVQSR) of VQSR.
keywords:
  - gatk4
  - variantrecalibrator
  - applyvqsr
  - selectvariants
  - mergevcfs
  - variant_calling
  - joint_germline
  - VQSR
modules:
  - gatk4/mergevcfs
  - gatk4/selectvariants
  - gatk4/variantrecalibrator
  - gatk4/applyvqsr
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - input:
      type: list
      description: |
        Vcf file and its index file containing the joint germline to be recalibrated
  - fasta:
      type: file
      description: The reference fasta file
      pattern: "*.fasta"
  - fai:
      type: file
      description: Index of reference fasta file
      pattern: "*.fasta.fai"
  - dict:
      type: file
      description: GATK sequence dictionary
      pattern: "*.dict"
  - allelespecific:
      type: boolean
      description: run allelespecific mode of vqsr modules.
      pattern: "{true,false}"
  - resources_SNP:
      type: val
      description: |
        resource vcfs, indexes and labels to be used as truth, training and known sites resources,
        vcf list imports the files into the module,
        resource_labels list contains file names which are passed to the command.
      pattern: "[[resource, vcfs, forvariantrecal], [resource, tbis, forvariantrecal], [resource, labels, forvariantrecal]]"
  - resources_INDEL:
      type: val
      description: |
        resource vcfs, indexes and labels to be used as truth, training and known sites resources,
        vcf list imports the files into the module,
        resource_labels list contains file names which are passed to the command.
      pattern: "[[resource, vcfs, forvariantrecal], [resource, tbis, forvariantrecal], [resource, labels, forvariantrecal]]"
  - annotation_SNP:
      type: list
      description: list of annotations to use for variantrecal filtering SNP mode.
      pattern: "['QD', 'FS', 'SOR']"
  - annotation_INDEL:
      type: list
      description: list of annotations to use for variantrecal filtering INDEL mode.
      pattern: "['QD', 'FS', 'SOR']"
  - create_rscript:
      type: boolean
      description: whether to generate rscript plots in variantrecal.
      pattern: "{true,false}"
  - truthsensitivity:
      type: val
      description: truthsensitivity cutoff for applyvqsr.
      pattern: "0.0-100.0"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - select_var_indel_vcf:
      type: file
      description: vcf file containing indels.
      pattern: "*.vcf.gz"
  - select_var_indel_index:
      type: file
      description: Index file for vcf containing indels.
      pattern: "*.vcf.gz.tbi"
  - select_var_snp_vcf:
      type: file
      description: vcf file containing snps.
      pattern: "*.vcf.gz"
  - select_var_snp_index:
      type: file
      description: Index file for vcf containing snps.
      pattern: "*.vcf.gz.tbi"
  - select_var_norecal_vcf:
      type: file
      description: vcf file containing other variants.
      pattern: "*.vcf.gz"
  - select_var_norecal_index:
      type: file
      description: Index file for vcf containing other variants.
      pattern: "*.vcf.gz.tbi"
  - recal_snp_file:
      type: file
      description: recalibration tables file from variantrecalibrator.
      pattern: "*.recal"
  - recal_snp_index:
      type: file
      description: Index file for the recalibration tables.
      pattern: "*.idx"
  - recal_snp_tranches:
      type: file
      description: Tranches file for the recalibration tables.
      pattern: "*.tranches"
  - vqsr_snp_vcf:
      type: file
      description: joint vcf file recalibrated using applyvqsr.
      pattern: "*.vcf.gz"
  - vqsr_snp_index:
      type: file
      description: Index file for recalibrated joint vcf.
      pattern: "*.vcf.gz.tbi"
  - recal_indel_file:
      type: file
      description: recalibration tables file from variantrecalibrator.
      pattern: "*.recal"
  - recal_indel_index:
      type: file
      description: Index file for the recalibration tables.
      pattern: "*.idx"
  - recal_indel_tranches:
      type: file
      description: Tranches file for the recalibration tables.
      pattern: "*.tranches"
  - vqsr_indel_vcf:
      type: file
      description: joint vcf file recalibrated using applyvqsr.
      pattern: "*.vcf.gz"
  - vqsr_indel_index:
      type: file
      description: Index file for recalibrated joint vcf.
      pattern: "*.vcf.gz.tbi"
  - merged_recal_vcf:
      type: file
      description: vcf file containing merged, recalibrated vcf.
      pattern: "*.vcf.gz"
  - merged_recal_tbi:
      type: file
      description: Index file merged recalivrated vcf.
      pattern: "*.vcf.gz.tbi"
authors:
  - '@GCJMackenzie'
