name: bcftools_filter
description: Filters VCF files
keywords:
  - variant calling
  - filtering
  - VCF
tools:
  - filter:
      description: |
        Apply fixed-threshold filters to VCF files.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF input file
      pattern: "*.{vcf,bcf,vcf.gz,bcf.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF filtered output file
      pattern: "*.{vcf,bcf,vcf.gz,bcf.gz}"
  - csi:
      type: file
      description: Default VCF file index
      pattern: "*.csi"
  - tbi:
      type: file
      description: Alternative VCF file index
      pattern: "*.tbi"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@joseespinosa"
  - "@drpatelh"
maintainers:
  - "@joseespinosa"
  - "@drpatelh"
