---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::coreutils=9.5
  - conda-forge::grep=3.11
  - conda-forge::gzip=1.13
  - conda-forge::lbzip2=2.5
  - conda-forge::sed=4.8
  - conda-forge::tar=1.34
