name: cnvkit_genemetrics
description: Copy number variant detection from high-throughput sequencing data
keywords:
  - cnvkit
  - bam
  - fasta
  - copy number
tools:
  - cnvkit:
      description: |
        CNVkit is a Python library and command-line software toolkit to infer and visualize copy number from high-throughput DNA sequencing data. It is designed for use with hybrid capture, including both whole-exome and custom target panels, and short-read sequencing platforms such as Illumina and Ion Torrent.
      homepage: https://cnvkit.readthedocs.io/en/stable/index.html
      documentation: https://cnvkit.readthedocs.io/en/stable/index.html
      licence: ["Apache-2.0"]
      identifier: biotools:cnvkit
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - cnr:
        type: file
        description: CNR file
        pattern: "*.cnr"
    - cns:
        type: file
        description: CNS file [Optional]
        pattern: "*.cns"
output:
  - tsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tsv":
          type: file
          description: TSV file
          pattern: "*.tsv"
  - cnn:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.cnn":
          type: file
          description: CNN file
          pattern: "*.cnn"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@adamrtalbot"
  - "@marrip"
  - "@priesgo"
maintainers:
  - "@adamrtalbot"
  - "@marrip"
  - "@priesgo"
