# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "snpsift_annmem"
description: |
  High-performance annotation of VCF files using memory-optimized databases.
  Supports two modes: database creation (ext.create=true) and VCF annotation (default).
keywords:
  - vcf
  - annotation
  - snpsift
  - variant
  - database
tools:
  - snpsift:
      description: "Genetic variant annotations and functional effect prediction toolbox"
      homepage: "https://pcingola.github.io/SnpEff/snpsift/annotate_mem/"
      documentation: "https://pcingola.github.io/SnpEff/snpsift/annotate_mem/"
      tool_dev_url: "https://github.com/pcingola/SnpSift"
      doi: "10.3389/fgene.2012.00035"
      licence: ["MIT"]
      identifier: biotools:snpsift
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test' ]`
    - vcf:
        type: file
        description: |
          In create mode: VCF file to build database from.
          In annotate mode: VCF file to annotate.
        pattern: "*.{vcf,vcf.gz}"
    - vcf_tbi:
        type: file
        description: Tabix index for input VCF (optional in annotate mode)
        pattern: "*.{tbi}"
    - fields:
        type: string
        description: |
          Comma-separated list of INFO fields to include in database (create mode only).
          Use empty string in annotate mode.
  - - databases:
        type: file
        description: List of annotation VCF database files (annotate mode only, empty list for create mode)
        pattern: "*.{vcf,vcf.gz}"
    - dbs_tbis:
        type: file
        description: List of tabix indices for database files (annotate mode only)
        pattern: "*.{tbi}"
    - db_vardbs:
        type: directory
        description: List of pre-built .snpsift.vardb directories (annotate mode only)
        pattern: "*.snpsift.vardb"
    - db_fields:
        type: list
        description: List of comma-separated INFO fields for each database (annotate mode only)
    - db_prefixes:
        type: list
        description: List of prefixes to add to annotated field names (annotate mode only)
output:
  database:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test' ]`
      - "*.snpsift.vardb":
          type: directory
          description: SnpSift vardb directory (create mode only, optional)
          pattern: "*.snpsift.vardb"
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test' ]`
      - "*.vcf.gz":
          type: file
          description: Annotated VCF file (annotate mode only, optional)
          pattern: "*.vcf.gz"
      - "*.vcf.gz.tbi":
          type: file
          description: Tabix index for annotated VCF (annotate mode only, optional)
          pattern: "*.vcf.gz.tbi"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@friederike-hanssen"
maintainers:
  - "@friederike-hanssen"
