name: strelka_germline
description: Strelka2 is a fast and accurate small variant caller optimized for analysis
  of germline variation
keywords:
  - variantcalling
  - germline
  - wgs
  - vcf
  - variants
tools:
  - strelka:
      description: Strelka calls somatic and germline small variants from mapped sequencing
        reads
      homepage: https://github.com/Illumina/strelka
      documentation: https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md
      tool_dev_url: https://github.com/Illumina/strelka
      doi: 10.1038/s41592-018-0051-x
      licence: ["GPL v3"]
      identifier: biotools:strelka
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test']
    - input:
        type: file
        description: BAM/CRAM file
        pattern: "*.{bam,cram}"
    - input_index:
        type: file
        description: BAM/CRAI index file
        pattern: "*.{bai,crai}"
    - target_bed:
        type: file
        description: BED file containing target regions for variant calling
        pattern: "*.{bed}"
    - target_bed_index:
        type: file
        description: Index for BED file containing target regions for variant calling
        pattern: "*.{bed.tbi}"
  - - fasta:
        type: file
        description: Genome reference FASTA file
        pattern: "*.{fa,fasta}"
  - - fai:
        type: file
        description: Genome reference FASTA index file
        pattern: "*.{fa.fai,fasta.fai}"
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*variants.vcf.gz":
          type: file
          description: gzipped germline variant file
          pattern: "*.{vcf.gz}"
  - vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*variants.vcf.gz.tbi":
          type: file
          description: index file for the vcf file
          pattern: "*.vcf.gz.tbi"
  - genome_vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*genome.vcf.gz":
          type: file
          description: variant records and compressed non-variant blocks
          pattern: "*_genome.vcf.gz"
  - genome_vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*genome.vcf.gz.tbi":
          type: file
          description: index file for the genome_vcf file
          pattern: "*_genome.vcf.gz.tbi"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@arontommi"
maintainers:
  - "@arontommi"
