# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "vcf_annotate_snpsift"
description: Annotate VCF files using SnpSift annotateMem with multiple databases
keywords:
  - vcf
  - annotation
  - snpsift
  - variant
components:
  - snpsift/annmem/create_db
  - snpsift/annmem
input:
  - ch_vcf:
      type: file
      description: |
        Channel containing VCF files with metadata
        Structure: [val(meta), path(vcf)]
      pattern: "*.{vcf,vcf.gz}"
  - val_db_configs:
      type: list
      description: |
        List of unified configuration maps for each database.
        Each map contains:
        - vcf: Path to annotation VCF file (required)
        - tbi: Path to tabix index (required)
        - fields: Comma-separated INFO fields to annotate (optional)
        - prefix: Prefix for annotated field names (optional)
        - vardb: Path to pre-built .snpsift.vardb directory (optional)
  - val_create_dbs:
      type: boolean
      description: |
        Whether to create .snpsift.vardb databases for entries without pre-built vardbs.
        When true, creates databases for faster annotation.
        When false, uses pre-built vardbs if specified, otherwise processes VCF directly.
output:
  - vcf_tbi:
      type: file
      description: |
        Channel containing annotated VCF files with metadata and index
        Structure: [val(meta), path(vcf), path(tbi)]
      pattern: "*.{vcf.gz}"
  # versions are emitted via topic channel
authors:
  - "@friederike-hanssen"
maintainers:
  - "@friederike-hanssen"
