# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/meta-schema.json
name: "vcf_annotate_snpsift"
description: Annotate VCF files using SnpSift annotateMem with multiple databases
keywords:
  - vcf
  - annotation
  - snpsift
  - variant
components:
  - snpsift/annmem
input:
  - ch_vcf:
      type: file
      description: |
        Channel containing VCF files with metadata
        Structure: [val(meta), path(vcf)]
      pattern: "*.{vcf,vcf.gz}"
  - ch_db_tuple:
      type: tuple
      description: |
        Tuple containing prepared database information:
        [[databases], [tbis], [vardbs], [fields], [prefixes]]
output:
  - vcf_tbi:
      type: file
      description: |
        Channel containing annotated VCF files with metadata and index
        Structure: [val(meta), path(vcf), path(tbi)]
      pattern: "*.{vcf.gz}"
authors:
  - "@friederike-hanssen"
maintainers:
  - "@friederike-hanssen"
