FROM ewels/multiqc:v1.4

LABEL \
  author="Maxime Garcia" \
  description="MultiQC image used in CAW" \
  maintainer="maxime.garcia@scilifelab.se"

# Create UPPMAX directories
RUN mkdir /pica /proj /scratch /sw
