name: bcftools_mpileup
description: Compresses VCF files
keywords:
  - variant calling
  - mpileup
  - VCF
tools:
  - mpileup:
      description: |
        Generates genotype likelihoods at each genomic position with coverage.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: http://www.htslib.org/doc/bcftools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:bcftools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Input BAM file
        pattern: "*.{bam}"
    - intervals:
        type: file
        description: Input intervals file. A file (commonly '.bed') containing regions
          to subset
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: FASTA reference file
        pattern: "*.{fasta,fa}"
  - - save_mpileup:
        type: boolean
        description: Save mpileup file generated by bcftools mpileup
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*vcf.gz":
          type: file
          description: VCF gzipped output file
          pattern: "*.{vcf.gz}"
  - tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*vcf.gz.tbi":
          type: file
          description: tabix index file
          pattern: "*.{vcf.gz.tbi}"
  - stats:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*stats.txt":
          type: file
          description: Text output file containing stats
          pattern: "*{stats.txt}"
  - mpileup:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.mpileup.gz":
          type: file
          description: mpileup gzipped output for all positions
          pattern: "{*.mpileup.gz}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@joseespinosa"
  - "@drpatelh"
maintainers:
  - "@joseespinosa"
  - "@drpatelh"
