name: msisensor_scan

description: Scan a reference genome to get microsatellite & homopolymer information
keywords:
  - homoploymer,microsatellite
tools:
  - msisensor:
      description: MSIsensor is a C++ program to detect replication slippage variants at microsatellite regions, and differentiate them as somatic or germline.
      homepage: https://github.com/ding-lab/msisensor
      documentation: None
      tool_dev_url: None
      doi: "10.1093/bioinformatics/btt755"
      licence: ['MIT']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file
      pattern: "*.{fa,fasta}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - txt:
      type: file
      description: MSIsensor scan output file of homopolymers & minisatellites
      pattern: "*.msisensor_scan.txt"

authors:
  - "@kevbrick"
