name: "varlociraptor_estimatealignmentproperties"
description: In order to judge about candidate indel and structural variants, Varlociraptor
  needs to know about certain properties of the underlying sequencing experiment in
  combination with the used read aligner.
keywords:
  - estimation
  - alignment
  - variants
tools:
  - "varlociraptor":
      description: "Flexible, uncertainty-aware variant calling with parameter free
        filtration via FDR control."
      homepage: "https://varlociraptor.github.io/docs/estimating/"
      documentation: "https://varlociraptor.github.io/docs/estimating/"
      tool_dev_url: "https://github.com/varlociraptor/varlociraptor"
      doi: "10.1186/s13059-020-01993-6"
      licence: ["GPL v3"]
      identifier: biotools:varlociraptor
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: http://edamontology.org/format_2572 # BAM
    - bai:
        type: file
        description: Index of sorted BAM/CRAM/SAM file
        pattern: "*.{bai,crai,sai}"
        ontologies:
          - edam: http://edamontology.org/format_3327 # BAI
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Reference fasta file
        pattern: "*.{fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference index information
          e.g. [ id:'test', single_end:false ]
    - fai:
        type: file
        description: Index for reference fasta file (must be with samtools index)
        pattern: "*.{fai}"
        ontologies: []
output:
  alignment_properties_json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.alignment-properties.json":
          type: file
          description: File containing alignment properties
          pattern: "*.alignment-properties.json"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@FriederikeHanssen"
maintainers:
  - "@FriederikeHanssen"
  - "@famosab"
