# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fgbio_copyumifromreadname"
description: Copies the UMI at the end of a bam files read name to the RX tag.
keywords:
  - sort
  - example
  - genomics
tools:
  - "fgbio":
      description: "A set of tools for working with genomic and high throughput sequencing
        data, including UMIs"
      homepage: http://fulcrumgenomics.github.io/fgbio/
      documentation: http://fulcrumgenomics.github.io/fgbio/tools/latest/CallDuplexConsensusReads.html
      tool_dev_url: https://github.com/fulcrumgenomics/fgbio
      licence: ["MIT"]
      identifier: biotools:fgbio

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`

    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
          - edam: "http://edamontology.org/format_2573" # CRAM
          - edam: "http://edamontology.org/format_3462" # SAM

    - bai:
        type: file
        description: Index for bam file
        pattern: "*.{bai}"
        ontologies:
          - edam: "http://edamontology.org/format_2572" # BAM
          - edam: "http://edamontology.org/format_2573" # CRAM
          - edam: "http://edamontology.org/format_3462" # SAM

output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bam":
          type: file
          description: Sorted BAM file
          pattern: "*.{bam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bai":
          type: file
          description: Index for bam file
          pattern: "*.{bai}"
          ontologies:
            - edam: "http://edamontology.org/format_3327" # BAI
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@sppearce"
maintainers:
  - "@sppearce"
