name: svdb_merge
description: The merge module merges structural variants within one or more vcf files.
keywords:
  - structural variants
tools:
  - svdb:
      description: structural variant database software
      homepage: https://github.com/J35P312/SVDB
      documentation: https://github.com/J35P312/SVDB/blob/master/README.md
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - priority:
      type: list
      description: prioritise the input vcf files according to this list, e.g ['tiddit','cnvnator']
  - vcfs:
      type: list
      description: Two or more VCF files. Order of files should correspond to the order of tags used for priority.
      pattern: "*.{vcf,vcf.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf:
      type: file
      description: merged VCF file
      pattern: "*_sv_merge.vcf.gz"
authors:
  - "@ramprasadn"
