name: manta_somatic
description: Manta calls structural variants (SVs) and indels from mapped paired-end
  sequencing reads. It is optimized for analysis of germline variation in small sets
  of individuals and somatic variation in tumor/normal sample pairs.
keywords:
  - somatic
  - wgs
  - wxs
  - panel
  - vcf
  - structural variants
  - small indels
tools:
  - manta:
      description: Structural variant and indel caller for mapped sequencing data
      homepage: https://github.com/Illumina/manta
      documentation: https://github.com/Illumina/manta/blob/v1.6.0/docs/userGuide/README.md
      tool_dev_url: https://github.com/Illumina/manta
      doi: "10.1093/bioinformatics/btv710"
      licence: ["GPL v3"]
      identifier: biotools:manta_sv
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input_normal:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
    - input_index_normal:
        type: file
        description: BAM/CRAM/SAM index file
        pattern: "*.{bai,crai,sai}"
    - input_tumor:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
    - input_index_tumor:
        type: file
        description: BAM/CRAM/SAM index file
        pattern: "*.{bai,crai,sai}"
    - target_bed:
        type: file
        description: BED file containing target regions for variant calling
        pattern: "*.{bed}"
    - target_bed_tbi:
        type: file
        description: Index for BED file containing target regions for variant calling
        pattern: "*.{bed.tbi}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: Genome reference FASTA file
        pattern: "*.{fa,fasta}"
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fai:
        type: file
        description: Genome reference FASTA index file
        pattern: "*.{fa.fai,fasta.fai}"
  - - config:
        type: file
        description: Manta configuration file
        pattern: "*.{ini,conf,config}"
output:
  - candidate_small_indels_vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.candidate_small_indels.vcf.gz":
          type: file
          description: Gzipped VCF file containing variants
          pattern: "*.{vcf.gz}"
  - candidate_small_indels_vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.candidate_small_indels.vcf.gz.tbi":
          type: file
          description: Index for gzipped VCF file containing variants
          pattern: "*.{vcf.gz.tbi}"
  - candidate_sv_vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.candidate_sv.vcf.gz":
          type: file
          description: Gzipped VCF file containing variants
          pattern: "*.{vcf.gz}"
  - candidate_sv_vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.candidate_sv.vcf.gz.tbi":
          type: file
          description: Index for gzipped VCF file containing variants
          pattern: "*.{vcf.gz.tbi}"
  - diploid_sv_vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.diploid_sv.vcf.gz":
          type: file
          description: Gzipped VCF file containing variants
          pattern: "*.{vcf.gz}"
  - diploid_sv_vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.diploid_sv.vcf.gz.tbi":
          type: file
          description: Index for gzipped VCF file containing variants
          pattern: "*.{vcf.gz.tbi}"
  - somatic_sv_vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.somatic_sv.vcf.gz":
          type: file
          description: Gzipped VCF file containing variants
          pattern: "*.{vcf.gz}"
  - somatic_sv_vcf_tbi:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.somatic_sv.vcf.gz.tbi":
          type: file
          description: Index for gzipped VCF file containing variants
          pattern: "*.{vcf.gz.tbi}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@FriederikeHanssen"
  - "@nvnieuwk"
maintainers:
  - "@FriederikeHanssen"
  - "@nvnieuwk"
