name: bcftools_annotate
description: Add or remove annotations.
keywords:
  - bcftools
  - annotate
  - vcf
  - remove
  - add
tools:
  - annotate:
      description: Add or remove annotations.
      homepage: http://samtools.github.io/bcftools/bcftools.html
      documentation: https://samtools.github.io/bcftools/bcftools.html#annotate
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:bcftools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: Query VCF or BCF file, can be either uncompressed or compressed
        ontologies: []
    - index:
        type: file
        description: Index of the query VCF or BCF file
        ontologies: []
    - annotations:
        type: file
        description: Bgzip-compressed file with annotations
        ontologies: []
    - annotations_index:
        type: file
        description: Index of the annotations file
        ontologies: []
  - header_lines:
      type: file
      description: Contains lines to append to the output VCF header
      ontologies: []
  - rename_chrs:
      type: file
      description: Rename annotations according to this file containing "old_name new_name\n"
        pairs separated by whitespaces, each on a separate line.
      ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.{vcf,vcf.gz,bcf,bcf.gz}":
          type: file
          description: Compressed annotated VCF file
          pattern: "*{vcf,vcf.gz,bcf,bcf.gz}"
          ontologies: []
  tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tbi":
          type: file
          description: Alternative VCF file index
          pattern: "*.tbi"
          ontologies: []
  csi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.csi":
          type: file
          description: Default VCF file index
          pattern: "*.csi"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@projectoriented"
  - "@ramprasadn"
maintainers:
  - "@projectoriented"
  - "@ramprasadn"
