name: msisensorpro_scan

description: Scan the reference genome to get microsatellites information
keywords:
  - microsatellite
tools:
  - msisensor:
      description: MSIsensor-pro is an updated version of msisensor
      homepage: https://github.com/xjtu-omics/msisensor-pro
      documentation: None
      tool_dev_url: None
      doi: "doi.org/10.1016/j.gpb.2020.02.001"
      licence: ['free for non-commercial use by academic, government, and non-profit/not-for-profit institutions']

input:
  - fasta:
      type: file
      description: FASTA file
      pattern: "*.{fa,fasta}"

output:
  - list:
      type: file
      description: MSIsensor-pro scan output file of minisatellites
      pattern: "*.list"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@maxulysse"
