name: gatk4_mutect2
description: Call somatic SNVs and indels via local assembly of haplotypes.
keywords:
  - gatk4
  - haplotype
  - indels
  - mutect2
  - snvs
  - somatic
tools:
  - gatk4:
      description: |
        Developed in the Data Sciences Platform at the Broad Institute, the toolkit offers a wide variety of tools
        with a primary focus on variant discovery and genotyping. Its powerful processing engine
        and high-performance computing features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      doi: 10.1158/1538-7445.AM2017-3590
      licence: ["Apache-2.0"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test']
    - input:
        type: list
        description: list of BAM files, also able to take CRAM as an input
        pattern: "*.{bam/cram}"
    - input_index:
        type: list
        description: list of BAM file indexes, also able to take CRAM indexes as an
          input
        pattern: "*.{bam.bai/cram.crai}"
    - intervals:
        type: file
        description: Specify region the tools is run on.
        pattern: ".{bed,interval_list}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fasta:
        type: file
        description: The reference fasta file
        pattern: "*.fasta"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - fai:
        type: file
        description: Index of reference fasta file
        pattern: "*.fasta.fai"
        ontologies: []
  - - meta4:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. [ id:'genome' ]
    - dict:
        type: file
        description: GATK sequence dictionary
        pattern: "*.dict"
        ontologies: []
  - alleles:
      type: file
      description: vcf file to be used to force-call alleles.
      pattern: "*.vcf.gz"
      ontologies:
        - edam: http://edamontology.org/format_3989 # GZIP format
  - alleles_tbi:
      type: file
      description: Index file for alleles to be force-called.
      pattern: "*.vcf.gz.tbi"
      ontologies: []
  - germline_resource:
      type: file
      description: Population vcf of germline sequencing, containing allele fractions.
      pattern: "*.vcf.gz"
      ontologies:
        - edam: http://edamontology.org/format_3989 # GZIP format
  - germline_resource_tbi:
      type: file
      description: Index file for the germline resource.
      pattern: "*.vcf.gz.tbi"
      ontologies: []
  - panel_of_normals:
      type: file
      description: vcf file to be used as a panel of normals.
      pattern: "*.vcf.gz"
      ontologies:
        - edam: http://edamontology.org/format_3989 # GZIP format
  - panel_of_normals_tbi:
      type: file
      description: Index for the panel of normals.
      pattern: "*.vcf.gz.tbi"
      ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: A Groovy map containing sample information
      - "*.vcf.gz":
          type: file
          description: compressed vcf file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  tbi:
    - - meta:
          type: map
          description: A Groovy map containing sample information
      - "*.tbi":
          type: file
          description: Index of vcf file
          pattern: "*vcf.gz.tbi"
          ontologies: []
  stats:
    - - meta:
          type: map
          description: A Groovy map containing sample information
      - "*.stats":
          type: file
          description: Stats file that pairs with output vcf file
          pattern: "*vcf.gz.stats"
          ontologies: []
  f1r2:
    - - meta:
          type: map
          description: A Groovy map containing sample information
      - "*.f1r2.tar.gz":
          type: file
          description: file containing information to be passed to LearnReadOrientationModel
            (only outputted when tumor_normal_pair mode is run)
          pattern: "*.f1r2.tar.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@GCJMackenzie"
  - "@ramprasadn"
maintainers:
  - "@GCJMackenzie"
  - "@ramprasadn"
  