# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "xengsort_classify"
description: Xenograft read sorting using Xengsort
keywords:
  - classify
  - xenograft
  - k-mer
  - reference
tools:
  - "xengsort":
      description: "A fast xenograft read sorter based on space-efficient k-mer hashing."
      homepage: "https://gitlab.com/genomeinformatics/xengsort"
      documentation: "https://gitlab.com/genomeinformatics/xengsort"
      tool_dev_url: "https://gitlab.com/genomeinformatics/xengsort"
      doi: "10.4230/LIPIcs.WABI.2020.4"
      licence: ["MIT"]
      identifier: null

input:
  ### Add a description of all of the variables used as input
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
        ontologies: []

  - index_folder:
      type: directory
      description: |
        xengsort index directory containing the .hash and .info files
        generated by the xengsort index tool.
      ontologies: []

output:
  graft_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*-graft.*fq.gz":
          type: file
          description: |
            Output reads that map to the graft references
          pattern: "*-graft.*fq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  host_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*-host.*fq.gz":
          type: file
          description: |
            Output reads that map to the host references
          pattern: "*-host.*fq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  both_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*-both.*fq.gz":
          type: file
          description: |
            Output reads that map to both references
          pattern: "*-both.*fq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  neither_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*-neither.*fq.gz":
          type: file
          description: |
            Output reads that map to the neither of the references
          pattern: "*-neither.*fq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  ambiguous_fastq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*-ambiguous.*fq.gz":
          type: file
          description: |
            Ambiguous reads output
          pattern: "*-ambiguous.*fq.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions_xengsort_classify:
    - - "${task.process}":
          type: string
          description: The process the versions were collected from
      - "xengsort":
          type: string
          description: The name of the tool
      - "xengsort --version":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - xengsort:
          type: string
          description: The name of the tool
      - xengsort --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@xinghansun"
maintainers:
  - "@xinghansun"
