name: bwa_index
description: Create BWA index for reference genome
keywords:
  - index
  - fasta
  - genome
  - reference
tools:
  - bwa:
      description: |
        BWA is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: http://bio-bwa.sourceforge.net/
      documentation: https://bio-bwa.sourceforge.net/bwa.shtml
      arxiv: arXiv:1303.3997
      licence: ["GPL-3.0-or-later"]
      identifier: "biotools:bwa"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input genome fasta file
        ontologies:
          - edam: "http://edamontology.org/data_2044" # Sequence
          - edam: "http://edamontology.org/format_1929" # FASTA
output:
  - index:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
      - bwa:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
          pattern: "*.{amb,ann,bwt,pac,sa}"
          ontologies:
            - edam: "http://edamontology.org/data_3210" # Genome index
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@maxulysse"
maintainers:
  - "@drpatelh"
  - "@maxulysse"
  - "@gallvp"
