FROM broadinstitute/gatk3:3.8-0

LABEL \
  author="Maxime Garcia" \
  description="GATK image for use in Sarek" \
  maintainer="maxime.garcia@scilifelab.se"

ENV GATK_HOME=/usr

# Create UPPMAX directories
RUN mkdir /pica /proj /scratch /sw
