name: samtools_mpileup
description: BAM
keywords:
  - mpileup
  - bam
  - sam
  - cram
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
    - intervals:
        type: file
        description: Interval FILE
        pattern: "*.bed"
  - - fasta:
        type: file
        description: FASTA reference file
        pattern: "*.{fasta,fa}"
output:
  - mpileup:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.mpileup.gz":
          type: file
          description: mpileup file
          pattern: "*.{mpileup}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@joseespinosa"
maintainers:
  - "@drpatelh"
  - "@joseespinosa"
