name: sentieon_tnscope
description: TNscope algorithm performs somatic variant calling on the tumor-normal
  matched pair or the tumor only data, using a Haplotyper algorithm.
keywords:
  - tnscope
  - sentieon
  - variant_calling
tools:
  - sentieon:
      description: |
        Sentieon® provides complete solutions for secondary DNA/RNA analysis for a variety of sequencing platforms, including short and long reads.
        Our software improves upon BWA, STAR, Minimap2, GATK, HaplotypeCaller, Mutect, and Mutect2 based pipelines and is deployable on any generic-CPU-based computing system.
      homepage: https://www.sentieon.com/
      documentation: https://www.sentieon.com/
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information.
          e.g. [ id:'test' ]
    - input:
        type: file
        description: One or more BAM or CRAM files.
        pattern: "*.{bam,cram}"
    - input_index:
        type: file
        description: Indices for the input files
        pattern: "*.{bai,crai}"
    - intervals:
        type: file
        description: bed or interval_list file containing interval in the reference
          that will be used in the analysis. Only recommended for large WGS data, else 
          the overhead may not be worth the additional parallelisation.
        pattern: "*.{bed,interval_list}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - fasta:
        type: file
        description: Genome fasta file
        pattern: "*.{fa,fasta}"
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - fai:
        type: file
        description: Index of the genome fasta file
        pattern: "*.fai"
  - - meta4:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - dbsnp:
        type: file
        description: Single Nucleotide Polymorphism database (dbSNP) file
        pattern: "*.vcf.gz"
  - - meta5:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - dbsnp_tbi:
        type: file
        description: Index of the Single Nucleotide Polymorphism database (dbSNP) file
        pattern: "*.vcf.gz.tbi"
  - - meta6:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - pon:
        type: file
        description: Single Nucleotide Polymorphism database (dbSNP) file
        pattern: "*.vcf.gz"
  - - meta7:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - pon_tbi:
        type: file
        description: Index of the Single Nucleotide Polymorphism database (dbSNP) file
        pattern: "*.vcf.gz.tbi"
  - - meta8:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - cosmic:
        type: file
        description: Catalogue of Somatic Mutations in Cancer (COSMIC) VCF file.
        pattern: "*.vcf.gz"
  - - meta9:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test' ]
    - cosmic_tbi:
        type: file
        description: Index of the Catalogue of Somatic Mutations in Cancer (COSMIC) VCF file.
        pattern: "*.vcf.gz.tbi"
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test' ]
      - "*.vcf.gz":
          type: file
          description: VCF file
          pattern: "*.{vcf.gz}"
  - index:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test' ]
      - "*.vcf.gz.tbi":
          type: file
          description: Index of the VCF file
          pattern: "*.vcf.gz.tbi"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@ramprasadn"
maintainers:
  - "@ramprasadn"
