name: cat_cat
description: A module for concatenation of gzipped or uncompressed files
keywords:
  - concatenate
  - gzip
  - cat
tools:
  - cat:
      description: Just concatenation
      homepage: None
      documentation: https://man7.org/linux/man-pages/man1/cat.1.html
      tool_dev_url: None
      licence: ["GPL-3.0-or-later"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - files_in:
      type: file
      description: List of compressed / uncompressed files
      pattern: "*"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - file_out:
      type: file
      description: Concatenated file. Will be gzipped if file_out ends with ".gz"
      pattern: "${file_out}"

authors:
  - "@erikrikarddaniel"
  - "@FriederikeHanssen"
