name: cat_cat
description: A module for concatenation of gzipped or uncompressed files
keywords:
  - concatenate
  - gzip
  - cat
tools:
  - cat:
      description: Just concatenation
      documentation: https://man7.org/linux/man-pages/man1/cat.1.html
      licence: ["GPL-3.0-or-later"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - files_in:
        type: file
        description: List of compressed / uncompressed files
        pattern: "*"
        ontologies: []
output:
  file_out:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - ${prefix}:
          type: file
          description: Concatenated file. Will be gzipped if file_out ends with ".gz"
          pattern: "${file_out}"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@erikrikarddaniel"
  - "@FriederikeHanssen"
maintainers:
  - "@erikrikarddaniel"
  - "@FriederikeHanssen"
