name: "manta_convertinversions"
description: Manta calls structural variants (SVs) and indels from mapped paired-end sequencing reads. This script reformats inversions into single inverted sequence junctions which was the format used in Manta versions <= 1.4.0.
keywords:
  - structural variants
  - conversion
tools:
  - manta:
      description: Structural variant and indel caller for mapped sequencing data
      homepage: https://github.com/Illumina/manta
      documentation: https://github.com/Illumina/manta/blob/v1.6.0/docs/userGuide/README.md
      tool_dev_url: https://github.com/Illumina/manta
      doi: "10.1093/bioinformatics/btv710"
      licence: ["GPL v3"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: VCF file produces by Manta
      pattern: "*.vcf.gz"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - vcf:
      type: file
      description: VCF file with reformatted inversions
      pattern: "*.vcf.gz"
  - tbi:
      type: file
      description: TBI file produces by Manta
      pattern: "*.vcf.gz.tbi"
authors:
  - "@FriederikeHanssen"
