name: minimap2_index
description: Provides fasta index required by minimap2 alignment.
keywords:
  - index
  - fasta
  - reference
tools:
  - minimap2:
      description: |
        A versatile pairwise aligner for genomic and spliced nucleotide sequences.
      homepage: https://github.com/lh3/minimap2
      documentation: https://github.com/lh3/minimap2#uguide
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: |
        Reference database in FASTA format.
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - index:
      type: file
      description: Minimap2 fasta index.
      pattern: "*.mmi"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@yuukiiwa"
  - "@drpatelh"
maintainers:
  - "@yuukiiwa"
  - "@drpatelh"
