name: sentieon_dedup
description: Runs the sentieon tool LocusCollector followed by Dedup. LocusCollector collects read information that is used by Dedup which in turn marks or removes duplicate reads.
keywords:
  - mem
  - dedup
  - map
  - bam
  - cram
  - sentieon
tools:
  - sentieon:
      description: |
        Sentieon® provides complete solutions for secondary DNA/RNA analysis for a variety of sequencing platforms, including short and long reads.
        Our software improves upon BWA, STAR, Minimap2, GATK, HaplotypeCaller, Mutect, and Mutect2 based pipelines and is deployable on any generic-CPU-based computing system.
      homepage: https://www.sentieon.com/
      documentation: https://www.sentieon.com/
input:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information.
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file.
      pattern: "*.bam"
  - bai:
      type: file
      description: BAI file
      pattern: "*.bai"
  - fasta:
      type: file
      description: Genome fasta file
      pattern: "*.{fa,fasta}"
  - fasta_fai:
      type: file
      description: The index of the FASTA reference.
      pattern: "*.fai"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information.
        e.g. [ id:'test', single_end:false ]
  - cram:
      type: file
      description: CRAM file
      pattern: "*.cram"
  - crai:
      type: file
      description: CRAM index file
      pattern: "*.crai"
  - bam:
      type: file
      description: BAM file.
      pattern: "*.bam"
  - bai:
      type: file
      description: BAI file
      pattern: "*.bai"
  - score:
      type: file
      description: The score file indicates which reads LocusCollector finds are likely duplicates.
      pattern: "*.score"
  - metrics:
      type: file
      description: Output file containing the metrics data from Dedup.
      pattern: "*.metrics"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@asp8200"
