name: nf-core CI

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Nestflow
      run: |
        mkdir ${HOME}/tmp/nextflow && cd ${HOME}/tmp/nextflow
        wget -qO- get.nextflow.io | bash
        sudo ln -s ${HOME}/tmp/nextflow/nextflow /usr/local/bin/nextflow
    - name: Build References
      run: |
        ${GITHUB_WORKSPACE}/scripts/build_reference.sh --test SOMATIC --verbose
    - name: Run test
      run: |
        ${GITHUB_WORKSPACE}/scripts/run_test.sh --test SOMATIC --verbose
