name: nf-core branch protection
# This workflow is triggered on PRs to master branch on the repository
on:
  pull_request:
    branches:
    - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # PRs are only ok if coming from dev branch
      - name: Check PRs
        run: |
          [ ${GITHUB_REPOSITORY} = "nf-core/sarek" ] && [ ${GITHUB_HEAD_REF} = "dev" ]