name: nf-core CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Nextflow
      run: |
        wget -qO- get.nextflow.io | bash
        sudo ln -s nextflow /usr/local/bin/nextflow
    - name: Build References
      run: |
        ${GITHUB_WORKSPACE}/sarek/scripts/build_reference.sh --test SOMATIC --verbose
    - name: Run test
      run: |
        ${GITHUB_WORKSPACE}/sarek/scripts/run_test.sh --test SOMATIC --verbose