name: nf-core CI
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]  

jobs:
  build:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - uses: MaxUlysse/actions/install/nextflow@master
    - name: Download image
      run: |
        ${GITHUB_WORKSPACE}/scripts/download_image.sh -n docker --test SOMATIC
    - name: Build References
      run: |
        ${GITHUB_WORKSPACE}/scripts/build_reference.sh --test SOMATIC --verbose --memory 6.GB
    - name: Run test
      run: |
        ${GITHUB_WORKSPACE}/scripts/run_tests.sh --test SOMATIC --verbose --memory 6.GB