name: sentieon_dnamodelapply
description: modifies the input VCF file by adding the MLrejected FILTER to the variants
keywords:
  - dnamodelapply
  - vcf
  - filter
  - sentieon
tools:
  - sentieon:
      description: |
        Sentieon® provides complete solutions for secondary DNA/RNA analysis for a variety of sequencing platforms, including short and long reads.
        Our software improves upon BWA, STAR, Minimap2, GATK, HaplotypeCaller, Mutect, and Mutect2 based pipelines and is deployable on any generic-CPU-based computing system.
      homepage: https://www.sentieon.com/
      documentation: https://www.sentieon.com/
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - vcf:
        type: file
        description: INPUT VCF file
        pattern: "*.{vcf,vcf.gz}"
    - idx:
        type: file
        description: Index of the input VCF file
        pattern: "*.{tbi}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. `[ id:'test' ]`
    - fasta:
        type: file
        description: Genome fasta file
        pattern: "*.{fa,fasta}"
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. `[ id:'test' ]`
    - fai:
        type: file
        description: Index of the genome fasta file
        pattern: "*.fai"
  - - meta4:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. `[ id:'test' ]`
    - ml_model:
        type: file
        description: machine learning model file
        pattern: "*.model"
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.vcf.gz":
          type: file
          description: INPUT VCF file
          pattern: "*.{vcf,vcf.gz}"
  - index:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.vcf.gz.tbi":
          type: file
          description: Index of the input VCF file
          pattern: "*.{tbi}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@ramprasadn"
maintainers:
  - "@ramprasadn"
